#!/bin/bash
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

XIM_PROGRAM=/usr/bin/scim
XIM=SCIM
XIM_ARGS="-d"
if [ -f $XIM_PROGRAM ]; then
#	if [ "$LANG" = "zh" ]; then
#                export LC_ALL=zh_TW.UTF-8
#                export LANG=zh_TW.UTF-8
#	elif [ "$LANG" = "zh_cn" ]; then
#                export LC_ALL=zh_CN.UTF-8
#                export LANG=zh_CN.UTF-8
#	fi
	export GTK_IM_MODULE=xim
	export QT_IM_MODULE=xim
	export XMODIFIERS="@im=$XIM"
	$XIM_PROGRAM $XIM_ARGS
fi

/usr/local/bin/post-boot.sh 1> /tmp/init.log 2> /tmp/init.err &
httpd -c /etc/httpd.conf -h /
/usr/local/bin/node /usr/share/plate/chrome/content/daemon.js &

sleep 2

if [ -e /usr/bin/google-chrome ]; then 
	/usr/bin/google-chrome --kiosk http://localhost/usr/share/plate/chrome/content --user-data-dir=/root/.config/plate-chrome/ &
else 
	if [ -e /usr/bin/midori ]; then
		export MOZ_PLUGIN_PATH="/usr/lib/mozilla/plugins/:/usr/share/firefox/plugins/"
		/usr/bin/midori --config=/root/.config/plate-midori/ http://localhost/usr/share/plate/chrome/content &
	else
		/usr/local/bin/tableware &
	fi
fi

/usr/sbin/acpid &
#/usr/bin/openbox
#/usr/local/bin/tableware-wm
/usr/local/bin/uuwm
