#!/bin/bash
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

export GTK_IM_MODULE="scim"
/usr/bin/firefox -app /usr/share/plate/application.ini &

/usr/sbin/acpid &
/usr/bin/openbox
