#!/bin/bash
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

export GTK_IM_MODULE="scim"

if [ -e /usr/bin/google-chrome ]; then 

/usr/local/bin/post-boot.sh 1> /tmp/init.log 2> /tmp/init.err &
httpd -c /etc/httpd.conf -h / &
ifconfig lo 127.0.0.1 netmask 255.0.0.0
sleep 2
/usr/bin/google-chrome --kiosk http://localhost/usr/share/plate/chrome/content &

else 

/usr/bin/firefox -app /usr/share/plate/application.ini &

fi

/usr/sbin/acpid &
/usr/bin/openbox
