// Plate UI translation file, generated from po files

var i18n =	{

	home : {
		vi: "Khởi động",
		el: "Αρχική Σελίδα",
		fr: "Accueil",
		en: "Home",
		sk: "Štart",
		cs: "Start",
		pl: "Start",
		it: "Home",
		fi: "Käynnistä",
		kn: "Home",
		es: "Inicio",
		CN: "首页",
		ja: "ホーム",
		fa: "خانه",
		de: "Start",
		pt: "Página Inicial",
		ur: "صفحہ اول",
		TW: "回到主頁",
		sv: "Hem",
		ko: "시작",
		nl: "Start",
		gl: "Inicio",
		ru: "Главная страница",
	},

	menu : {
		vi: "Trình đơn",
		el: "Μενού",
		fr: "Menu",
		en: "Menu",
		sk: "Menu",
		cs: "Menu",
		pl: "Menu",
		it: "Menu",
		fi: "Valikko",
		kn: "Menu",
		es: "Menú",
		CN: "应用程序",
		ja: "メニュー",
		fa: "فهرست",
		de: "Menü",
		pt: "Menu",
		ur: "فہرست",
		TW: "執行程式",
		sv: "Meny",
		ko: "메뉴",
		nl: "Menu",
		gl: "Menú",
		ru: "Программы",
	},

	file : {
		vi: "Tập tin",
		el: "Αρχεία",
		fr: "Fichiers",
		en: "File",
		sk: "Súbor",
		cs: "Soubor",
		pl: "Plik",
		it: "File",
		fi: "Tiedosto",
		kn: "File",
		es: "Archivos",
		CN: "打开文件",
		ja: "ファイル",
		fa: "فایل",
		de: "Dateien",
		pt: "Arquivos",
		ur: "فائل",
		TW: "開啟檔案",
		sv: "Filer",
		ko: "파일",
		nl: "Bestanden",
		gl: "Ficheiros",
		ru: "Файл",
	},

	setting : {
		vi: "Tùy chọn",
		el: "Επιλογές",
		fr: "Paramètres",
		en: "Settings",
		sk: "Nastavenia",
		cs: "Nastavení",
		pl: "Ustawienia",
		it: "Preferenze",
		fi: "Asetukset",
		kn: "Settings",
		es: "Preferencias",
		CN: "设置系统",
		ja: "セッティング",
		fa: "مشخصه ها",
		de: "Einstellungen",
		pt: "Configurações",
		ur: "ترکیب",
		TW: "設定系統",
		sv: "Inställning",
		ko: "설정",
		nl: "Instellingen",
		gl: "Preferencias",
		ru: "Настройки",
	},

	welcome : {
		vi: "Chào mừng bạn đến với xPUD",
		el: "Καλώς ορίσατε στο xPUD",
		fr: "Bienvenue sur xPUD",
		en: "Welcome to xPUD",
		sk: "Vitajte v xPUD",
		cs: "Vítejte v xPUD",
		pl: "Witaj w xPUD",
		it: "Benvenuto in xPUD",
		fi: "Tervetuloa xPUD:iin",
		kn: "Welcome to xPUD",
		es: "Bienvenido a xPUD",
		CN: "欢迎使用 xPUD",
		ja: "xPUDに　ようこそ",
		fa: "خوش آمدید",
		de: "Willkommen zu xPUD",
		pt: "Bem vindo ao xPUD",
		ur: "میں خوش آمدید xPUD",
		TW: "歡迎使用 xPUD",
		sv: "Välkommen till xPUD",
		ko: "xPUD에 오신 것을 환영합니다",
		nl: "Welkom bij xPUD",
		gl: "Benvido a xPUD",
		ru: "Добро пожаловать в xPUD",
	},

	sys_info : {
		vi: "Thông tin hệ thống",
		el: "Πληροφορίες Συστήματος",
		fr: "Informations du système",
		en: "System Information",
		sk: "Systémové informácie",
		cs: "Informace o systému",
		pl: "Informacje o systemie",
		it: "Informazioni di Sistema",
		fi: "Järjestelmätiedot",
		kn: "System Information",
		es: "Información del sistema",
		CN: "系统信息",
		ja: "システム情報",
		fa: "اطلاعات سامانه",
		de: "Systeminformationen",
		pt: "Informações do sistema",
		ur: "سسٹم کے بارے میں معلومات",
		TW: "系統資訊",
		sv: "Systeminformation",
		ko: "시스템 정보",
		nl: "Systeeminformatie",
		gl: "Información do sistema",
		ru: "Системная Информация",
	},

	want_to : {
		vi: "Bạn có muốn tới",
		el: "Θελετε να:",
		fr: "Vous voulez:",
		en: "You may want to:",
		sk: "Čo chcete urobiť:",
		cs: "Co chcete udělat:",
		pl: "Co chcesz zrobić?",
		it: "Forse volete:",
		fi: "Haluatko:",
		kn: "You may want to:",
		es: "Quizás desee:",
		CN: "你也可以：",
		ja: "次のアクションもできます",
		fa: "شما ممکن است درخواست کنید که:",
		de: "Sie können:",
		pt: "Talvez você deseja:",
		ur: "اگر آپ چاہیں",
		TW: "你也可以：",
		sv: "Du kanske vill:",
		ko: "이런 것도 할 수 있습니다",
		nl: "wilt u:",
		gl: "Cecais desexe:",
		ru: "Желаете:",
	},

	quick_action : {
		fr: "Action rapide",
		en: "Quick Action",
		sk: "Rýchla akcia",
		cs: "Rychlá akce",
		kn: "Quick Action",
		fa: "عملیات سریع",
		de: "Nächste Schritte",
		TW: "快速選單",
		ko: "빠른 실행",
		nl: "Snelkeuze",
	},

	power_off : {
		vi: "Tắt máy",
		el: "Τερματισμός",
		fr: "Éteindre",
		en: "Power Off",
		sk: "Vypnúť",
		cs: "Vypnout",
		pl: "Wyłącz",
		it: "Arresto",
		fi: "Sammuta",
		kn: "Power Off",
		es: "Apagar",
		CN: "关机",
		ja: "電源を切る",
		fa: "خارج شدن",
		de: "Ausschalten",
		pt: "Desligar",
		ur: "پاور آف",
		TW: "關機",
		sv: "Stänga av",
		ko: "종료",
		nl: "Uitschakelen",
		gl: "Apagar",
		ru: "Выключить",
	},

	quit_now : {
		vi: "Bạn có muốn thoát ra bây giờ không",
		el: "Άμεσος τερματισμός;",
		fr: "Voulez-vous quitter maintenant ?",
		en: "Do you want to quit now?",
		sk: "Naozaj ukončiť?",
		cs: "Opravdu ukončit?",
		pl: "Jesteś pewien że chcesz zakończyć?",
		it: "Vuoi uscire adesso?",
		fi: "Haluatko lopetaa nyt?",
		kn: "Do you want to quit now?",
		es: "¿Desea Usted salir ahora?",
		CN: "确定要关机?",
		ja: "終了しますか？",
		fa: "آیا تصمیم دارید خارج شوید؟",
		de: "Möchten Sie jetzt ausschalten?",
		pt: "Você deseja sair agora?",
		ur: "پاور آف",
		TW: "確定要關機?",
		sv: "Vill du avsluta nu?",
		ko: "지금 종료하시겠습니까?",
		nl: "Wilt u nu afsluiten ?",
		gl: "Desexa vostede saír agora?",
		ru: "Действительно выйти?",
	},

	turn_off : {
		vi: "Tắt máy",
		el: "Τερματισμός",
		fr: "Éteindre",
		en: "Turn Off",
		sk: "Vypnúť",
		cs: "Vypnout",
		pl: "Wyłącz",
		it: "Spegni",
		fi: "Sammuta",
		kn: "Turn Off",
		es: "Apagar",
		CN: "关机",
		ja: "終了",
		fa: "خاموش کردن",
		de: "Ausschalten",
		pt: "Desligar",
		ur: "بند کر دیں",
		TW: "關機",
		sv: "Stäng av",
		ko: "종료",
		nl: "Afsluiten",
		gl: "Apagar",
		ru: "Выключить",
	},

	restart : {
		vi: "Khởi động lại",
		el: "Επανεκκίνηση",
		fr: "Redémarrer",
		en: "Restart",
		sk: "Reštartovať",
		cs: "Restartovat",
		pl: "Uruchom ponownie",
		it: "Riavvia",
		fi: "Käynnistä uudelleen",
		kn: "Restart",
		es: "Reiniciar",
		CN: "重启",
		ja: "再起動",
		fa: "باز آوری",
		de: "Neustart",
		pt: "Reiniciar",
		ur: "دوبارہ چلائیں",
		TW: "重新開機",
		sv: "Starta om",
		ko: "다시 시작",
		nl: "Herstarten",
		gl: "Reiniciar",
		ru: "Перезагрузить",
	},

	cancel_shutdown : {
		vi: "Thôi",
		el: "Ακύρωση",
		fr: "Abandonner",
		en: "Cancel",
		sk: "Zrušiť",
		cs: "Zrušit",
		pl: "Anuluj",
		it: "Annulla",
		fi: "Peruuta",
		kn: "Cancel",
		es: "Cancelar",
		CN: "取消",
		ja: "キャンセル",
		fa: "لغو کردن",
		de: "Abbrechen",
		pt: "Cancelar",
		ur: "کینسل",
		TW: "取消",
		sv: "Avbryt",
		ko: "취소",
		nl: "Annuleren",
		gl: "Cancelar",
		ru: "Отменить",
	},

	save_backup_to : {
		fr: "Sauvegarder sur",
		en: "Save backup to",
		sk: "Uložiť zálohu do",
		cs: "Uložit zálohu na",
		kn: "Save backup to",
		fa: "ذخیره کردن پشتیبان",
		de: "Einstellungen speichern unter",
		TW: "保留設定至",
		ko: "지정 디스크에 백업",
		nl: "Backup opslaan in",
	},

	power_off_desc : {
		vi: "Tắt máy tính này",
		el: "Τερματισμός Λειτουργίας",
		fr: "Éteindre l'ordinateur",
		en: "turn off this machine",
		sk: "vypnúť tento počítač",
		cs: "Vypnutí počítače",
		pl: "Wyłącz ten komputer",
		it: "Spegni il computer",
		fi: "Sammuta tietokone",
		kn: "turn off this machine",
		es: "Apagar su equipo",
		CN: "关闭这台电脑",
		ja: "PCの電源を切る",
		fa: "خاموش کردن سامانه",
		de: "Dieses Gerät ausschalten",
		pt: "Desligar computador",
		ur: "اس میشین کو بند کردیں",
		TW: "關閉這台電腦",
		sv: "Stäng av denna dator",
		ko: "컴퓨터를 종료합니다",
		nl: "Computer afsluiten",
		gl: "Apagar o seu equipo",
		ru: "Выключить компьютер",
	},

	switch_mode : {
		vi: "Chuyển tài khoản",
		el: "Αλλαγή Λειτουργικού",
		fr: "Changer de mode",
		en: "Switch Mode",
		sk: "Zmeniť systém",
		cs: "Změnit OS",
		pl: "Przełącz między systemami",
		it: "Cambia Sistema",
		fi: "Vaihda tila",
		kn: "Switch Mode",
		es: "Cambiar de SO",
		CN: "切换模式",
		ja: "モードを切換える",
		fa: "تغییر روش",
		de: "System wechseln",
		ur: "سسٹم تبدیلی",
		TW: "切換模式",
		sv: "Ändra läge",
		ko: "시스템 전환",
		nl: "Systeem wisselen",
		gl: "Cambiar de SO",
		ru: "Переключить режим",
	},

	switch_mode_desc : {
		vi: "Sang hệ điều hành khác",
		el: "Εναλλαγή Λειτουργικού Συστήματος",
		fr: "Basculer dans un autre OS",
		en: "toggle into other OS",
		sk: "spustiť iný operačný systém",
		cs: "Spuštění jiného operačního systému",
		pl: "przełącz do innego SO",
		it: "Passa ad un altro Sistema Operativo",
		fi: "Vaihda toiseen käyttöjärjestelmään",
		kn: "toggle into other OS",
		es: "Cambiar a otro sistema operativo",
		CN: "使用其他操作系統",
		ja: "別のOSに切換える",
		fa: "رفتن به سیستم عامل دیگر",
		de: "Anderes Betriebssystem starten",
		ur: "دوسرے آپریٹنگ سسٹم میں تبدیلی",
		TW: "使用其他作業系統",
		sv: "Starta andra operativsystem",
		ko: "다른 운영체제로 전환합니다",
		nl: "Ander OS kiezen",
		gl: "Cambiar a outro sistema operativo",
		ru: "загрузить другую ОС",
	},

	get_help : {
		vi: "Trợ giúp",
		el: "Βοήθεια",
		fr: "Obtenir de l'aide",
		en: "Get Help",
		sk: "Nápoveda",
		cs: "Nápověda",
		pl: "Pomoc",
		it: "Ottenere Aiuto",
		fi: "Ohjeet",
		kn: "Get Help",
		es: "Obtener ayuda",
		CN: "获取帮助",
		ja: "ヘルプしてもらう",
		fa: "درخواست کمک",
		de: "Hilfe",
		pt: "Obter ajuda",
		ur: "مدد حاصل کریں",
		TW: "取得幫助",
		sv: "Hjälp",
		ko: "도움말",
		nl: "hulp vragen",
		gl: "Obter axuda",
		ru: "Помощь",
	},

	get_help_desc : {
		vi: "và thông tin liên lạc",
		el: "και επικοινωνία",
		fr: "Informations et contact",
		en: "and contact information",
		sk: "a kontaktné informácie",
		cs: "Získání nápovědy",
		pl: "i informacje kontaktowe",
		it: "e informazioni/contatti",
		fi: "ja yhteystiedot",
		kn: "and contact information",
		es: "e información de contacto",
		CN: "了解xPUD的更多信息",
		ja: "その後xPUDの情報を見る",
		fa: "برقرای ارتباط",
		de: "und Kontaktinformationen",
		pt: "Aprender mais sobre o xPUD",
		ur: "اور رابطہ کیلئے معلومات",
		TW: "和更多資訊",
		sv: "och kontaktinformation",
		ko: "와(과) 연락 정보",
		nl: "en contact informatie",
		gl: "e información de contacto",
		ru: "и контакты",
	},

	help_about : {
		vi: "Giới thiệu",
		el: "Σχετικά με το xPUD",
		fr: "À propos de",
		en: "About",
		sk: "Info",
		cs: "O xPUD",
		pl: "O...",
		it: "Informazioni",
		fi: "Tietoja",
		kn: "About",
		es: "Acerca de",
		CN: "关于xPUD计划",
		ja: "xPUDについて",
		fa: "درباره سامانه",
		de: "Über",
		ur: "کے بارے میں",
		TW: "更多訊息",
		sv: "Om",
		ko: "xPUD에 대해서",
		nl: "Info",
		gl: "Acerca de",
		ru: "О",
	},

	help_info : {
		vi: "xPUD là dự án đang phát triển nhanh <br /> Thông tin liên hệ tại:",
		el: "Το xPUD είναι συνεχώς υπο ανάπτυξη <br /> Για περισσότερες πληροφορίες στο:",
		fr: "xPUD est un projet qui se développe rapidement. <br /> Pour plus d'informations, visitez :",
		en: "xPUD is a rapidly developing project. <br /> For more information, please go to:",
		sk: "xPUD je rýchlo rozvíjajúci sa projekt. <br /> Viac informácií:",
		cs: "xPUD je rychle se rozvíjející projekt. <br /> Pro více informací navštivte:",
		pl: "xPUD jest szybko rozwijającym się projektem. <br /> Jeśli chcesz dowiedzieć się więcej odwiedź:",
		it: "xPUD è un progetto in rapida evoluzione. <br /> Per maggiori informazioni, per favore visita: ",
		fi: "xPUD kehittyy nopeasti. <br /> Lisätietoja saat osoitteesta:",
		kn: "xPUD is a rapidly developing project. <br/> For more information, please go to:",
		es: "XPUD es un proyecto con un desarrollo muy rápido <br /> Para más información visite:",
		CN: "xPUD 是一个快速发展中的计划。请参阅：",
		ja: "xPUDは開発速度の早いプロジェクトです。 <br /> もっと情報が必要でしたら、次にお進みください：",
		fa: "xPUD به سرعت در حال گسترش است. <br /> برای اطلاعات بیشتر مراجعه کنید به:",
		de: "xPUD ist ein aktiv entwickeltes Projekt. <br /> Weitere Informationen unter:",
		ur: "تیزی سے ترقی پزیر پراجیکٹ ہے xPUD",
		TW: "xPUD 是一個快速發展中的計畫。請參閱：",
		sv: "xPUD är ett snabbt utvecklande projekt. <br /> För mer information, gå till:",
		ko: "xPUD는 빠르게 개발되고 있는 프로젝트입니다. <br /> 더 많은 정보를 보시려면 이곳을 방문해 주십시오:",
		nl: "xPUD is een rap groeiend project. <br /> Voor meer informatie, ga naar:",
		gl: "XPUD é un proxecto con un desenvolvemento moi rápido <br /> Para máis información visite:",
		ru: "xPUD быстро развивающийся проект. <br /> Больше информации можно получить здесь:",
	},

	help_done : {
		vi: "Hoàn tất",
		el: "OK",
		fr: "OK",
		en: "Done",
		sk: "OK",
		cs: "OK",
		pl: "Zakończono",
		it: "OK",
		fi: "OK",
		kn: "Done",
		es: "Hecho",
		CN: "完成",
		ja: "完成です",
		fa: "انجام شده",
		de: "OK",
		ur: "تمام",
		TW: "完成",
		sv: "Klar",
		ko: "확인",
		nl: "OK",
		gl: "Feito",
		ru: "Ок",
	},

	application : {
		vi: "Ứng dụng",
		el: "Εφαρμογές",
		fr: "Applications",
		en: "Applications",
		sk: "Programy",
		cs: "Aplikace",
		pl: "Programy",
		it: "Applicazioni",
		fi: "Sovellukset",
		kn: "Applications",
		es: "Aplicaciones",
		CN: "所有应用程序",
		ja: "アプリケーション",
		fa: "نرم افزارهای کاربردی",
		de: "Programme",
		pt: "Aplicações",
		ur: "پروگرامز",
		TW: "所有應用程式",
		sv: "Applikationer",
		ko: "프로그램",
		nl: "Programma's",
		gl: "Aplicacións",
		ru: "Программы",
	},

	web_app : {
		fr: "Applications en ligne",
		en: "Web App",
		sk: "Web aplikácie",
		cs: "Webové aplikace",
		kn: "Web App",
		fa: "نرم افزارهای تحت وب",
		de: "Webanwendungen",
		TW: "網頁捷徑",
		ko: "인터넷 프로그램",
		nl: "Web App",
	},

	web_browser : {
		vi: "Trình duyệt Web",
		el: "Περιηγητής",
		fr: "Navigateur Web",
		en: "Web Browser",
		sk: "Prehliadač",
		cs: "Prohlížeč",
		pl: "Przeglądarka WWW",
		it: "Browser Web",
		fi: "Internet-selain",
		kn: "Web Browser",
		es: "Navegador web",
		CN: "上网冲浪",
		ja: "ウェブブラウザ",
		fa: "مرورگر وب",
		de: "Internet Browser",
		pt: "Navegador de internet",
		ur: "ویب براوزر",
		TW: "網頁瀏覽器",
		sv: "Webbläsare",
		ko: "인터넷 브라우저",
		nl: "Web Browser",
		gl: "Navegador web",
		ru: "Веб Браузер",
	},

	bt_client : {
		vi: "BitTorrent",
		el: "Πελάτης BitTorrent",
		fr: "Client BitTorrent",
		en: "BitTorrent Client",
		sk: "BitTorrent klient",
		cs: "Klient BitTorrentu",
		pl: "Klient BitTorrent",
		it: "Client BitTorrent",
		fi: "BitTorrent-asiakassovellus",
		kn: "BitTorrent Client",
		es: "Cliente BitTorrent",
		CN: "BT 下载",
		ja: "ビットトレント",
		fa: "کلاینت بیت تورنت",
		de: "BitTorrent Client",
		pt: "Cliente BitTorrent",
		ur: "BitTorrent پروگرام برائے",
		TW: "BT 下載",
		sv: "BitTorrent Klient",
		ko: "비트토렌트",
		nl: "BitTorrent Client",
		gl: "Cliente BitTorrent",
		ru: "Torrent клиент",
	},

	media_player : {
		vi: "Đa phương tiện",
		el: "Αναπαραγωγή Πολυμέσων",
		fr: "Lecteur Multimedia",
		en: "Media Player",
		sk: "Prehrávač médií",
		cs: "Přehrávač médií",
		pl: "Odtwarzacz multimedialny",
		it: "Lettore Multimediale",
		fi: "Mediasoitin",
		kn: "Media Player",
		es: "Reproductor multimedia",
		CN: "播放影音",
		ja: "メディアプレーヤ",
		fa: "اجرا کننده چند رسانه ای",
		de: "Media Player",
		pt: "Reprodutor multimédia",
		ur: "میڈیا پلیئر",
		TW: "影音播放",
		sv: "Mediaspelare",
		ko: "미디어 플레이어",
		nl: "Media Player",
		gl: "Reproductor multimedia",
		ru: "Аудио/Видео проигрыватель",
	},

	picture_viewer : {
		vi: "Quản lý ảnh",
		el: "Εικόνες",
		fr: "Visionneur d'images",
		en: "Picture Viewer",
		sk: "Prehliadač obrázkov",
		cs: "Prohlížeč obrázků",
		pl: "Przeglądarka obrazów",
		it: "Visualizzatore di Immagini",
		fi: "Kuvienkatseluohjelma",
		kn: "Picture Viewer",
		es: "Visor de imágenes",
		CN: "浏览图片",
		ja: "ピクチャービューア",
		fa: "نمایش دهنده تصاویر",
		de: "Bildbetrachter",
		pt: "Visualizador de imagens",
		ur: "تصویر دیکھنے کیلئے",
		TW: "圖片瀏覽",
		sv: "Bildvisare",
		ko: "사진 보기",
		nl: "Afbeeldingen Viewer",
		gl: "Visor de imaxes",
		ru: "Просмотрщик изображений",
	},

	text_editor : {
		vi: "Soạn thảo văn bản",
		el: "Κειμενογράφος",
		fr: "Éditeur de texte",
		en: "Text Editor",
		sk: "Textový editor",
		cs: "Textový editor",
		pl: "Edytor tekstu",
		it: "Editor di Testo",
		fi: "Tekstinmuokkain",
		kn: "Text Editor",
		es: "Editor de texto",
		CN: "编辑文字",
		ja: "テキストエディタ",
		fa: "ویرایشگر متن",
		de: "Text Editor",
		pt: "Editor de texto",
		ur: "ٹیکسٹ لکھنے کیلئے",
		TW: "文字編輯",
		sv: "Textredigerare",
		ko: "문서 편집",
		nl: "Tekstbewerker",
		gl: "Editor de texto",
		ru: "Текстовый редактор",
	},

	pdf_viewer : {
		vi: "PDF Viewer",
		el: "Ανάγνωση PDF",
		fr: "Visionneur de PDF",
		en: "PDF Viewer",
		sk: "Prehliadač PDF",
		cs: "Prohlížeč PDF",
		pl: "Przeglądarka plików PDF",
		it: "Visualizzatore di PDF",
		fi: "PDF-katselin",
		kn: "PDF Viewer",
		es: "Visor de PDF",
		CN: "阅读PDF",
		ja: "PDFビューア",
		fa: "نمایش دهنده PDF",
		de: "PDF Viewer",
		pt: "Visualizador de PDFs",
		ur: "دیکھنے کیلئے PDF",
		TW: "PDF 閱讀",
		sv: "PDF läsare",
		ko: "PDF 뷰어",
		nl: "PDF Viewer",
		gl: "Visor de PDF",
		ru: "Просмотрщик PDF",
	},

	terminal_emulator : {
		vi: "Terminal Emulator",
		el: "Τερματικό",
		fr: "Émulateur de terminal",
		en: "Terminal Emulator",
		sk: "Terminál",
		cs: "Terminál",
		pl: "Emulator terminala",
		it: "Emulatore di Teminale",
		fi: "Komentorivi",
		kn: "Terminal Emulator",
		es: "Emulador de terminal",
		CN: "使用终端",
		ja: "ターミナル　エミュレータ",
		fa: "ترمینال",
		de: "Terminal Emulator",
		pt: "Terminal",
		ur: "دیکھنے کیلئے PDF",
		TW: "終端機",
		sv: "Kommandotolk",
		ko: "터미널",
		nl: "Terminal Emulator",
		gl: "Emulador de terminal",
		ru: "Терминал/Коммандная строка",
	},

	setting_personal : {
		vi: "Cá nhân hóa",
		el: "Προσωπικά",
		fr: "Personnel",
		en: "Personal",
		sk: "Osobné nastavenia",
		cs: "Osobní nastavení",
		pl: "Ustawienia osobiste",
		it: "Personale",
		fi: "Henkilökohtaiset asetukset",
		kn: "Personal",
		es: "Personal",
		CN: "个人设置",
		ja: "個人設定",
		fa: "شحصی",
		de: "Persönliche Einstellungen",
		ur: "ذاتی",
		TW: "個人設定",
		sv: "Personliga inställningar",
		ko: "사용자 설정",
		nl: "Persoonlijk",
		gl: "Persoal",
		ru: "Персональные настройки",
	},

	setting_language : {
		vi: "Ngôn ngữ",
		el: "Γλώσσα",
		fr: "Langue",
		en: "Language",
		sk: "Jazyk",
		cs: "Jazyk",
		pl: "Język",
		it: "Lingua",
		fi: "Kieli",
		kn: "Language",
		es: "Idioma",
		CN: "语言选项",
		ja: "言語の選択",
		fa: "زبانها",
		de: "Sprache",
		ur: "زبان",
		TW: "語言選項",
		sv: "Språk",
		ko: "언어",
		nl: "Taal",
		gl: "Idioma",
		ru: "Язык",
	},

	setting_language_desc : {
		vi: "Chọn địa phương và kiểu bàn phím",
		el: "επιλογή locale και keymap",
		fr: "Choisir la langue et la disposition du clavier",
		en: "choose locale and keymap",
		sk: "jazyk a rozloženie klávesnice",
		cs: "Nastavení jazyka a klávesnice",
		pl: "wybierz język i układ klawiatury",
		it: "scegli la lingua e la configurazione della tastiera",
		fi: "valitse aluekohtaiset- ja näppäimistöasetukset",
		kn: "choose locale and keymap",
		es: "elegir el idioma y la distribución del teclado",
		CN: "切换语系和键盘",
		ja: "ローカライズとキーの切換",
		fa: "مکان مورد نظر خود را انتخاب کنید.",
		de: "Sprache und Tastenbelegung",
		ur: "جگہ اور کی بورڈ کا انتخاب",
		TW: "切換語系和鍵盤",
		sv: "språk- och tangentbordsinstälnningar",
		ko: "언어와 키보드를 선택하십시오",
		nl: "Kies taal en toetsenbord indeling",
		gl: "elixir o idioma e a distribución do teclado",
		ru: "Выберите язык и раскладку",
	},

	setting_time_date : {
		vi: "Thời gian",
		el: "Ημερομηνία και Ώρα",
		fr: "Date et heure",
		en: "Time & Date",
		sk: "Dátum a čas",
		cs: "Datum a čas",
		pl: "Data i czas",
		it: "Data e Ora",
		fi: "Aika ja päivämäärä",
		kn: "Time & Date",
		es: "Fecha y hora",
		CN: "时间与日期",
		ja: "時間と月日",
		fa: "تاریخ و وقت",
		de: "Datum und Uhrzeit",
		pt: "Relógio",
		ur: "وقت اور تاریخ",
		TW: "時間日期",
		sv: "Tid och Datum",
		ko: "시간과 날짜",
		nl: "Tijd & Datum",
		gl: "Data e hora",
		ru: "Дата и Время",
	},

	setting_time_date_desc : {
		vi: "Thay đổi thời gian hệ thống",
		el: "Αλλαγή ώρας συστήματος",
		fr: "Changer l'heure du système",
		en: "change system clock",
		sk: "Zmeniť dátum a čas",
		cs: "Nastavení data a času",
		pl: "ustaw zegar systemowy",
		it: "Cambia l'ora di Sistema",
		fi: "Aseta järjestelmän kello",
		kn: "change system clock",
		es: "Cambiar la hora del sistema",
		CN: "调整系统的日期与时间",
		ja: "システムの日時を変更",
		fa: "انجام تغییرات در ساعت",
		de: "Datum und Uhrzeit stellen",
		pt: "Atualize o relógio do sistema",
		ur: "سسٹم کے وقت کو تبدیل کریں",
		TW: "調整系統日期與時間",
		sv: "ändra systemtid",
		ko: "시스템 시간을 변경하십시오",
		nl: "Systeemklok aanpassen",
		gl: "Cambiar a hora do sistema",
		ru: "Настроить часы",
	},

	setting_backup : {
		vi: "Khôi phục",
		el: "Αντίγραφο ασφαλείας",
		fr: "Sauvegarde",
		en: "Backup",
		sk: "Zálohovať",
		cs: "Zálohování",
		pl: "Kopia danych",
		it: "Copia di Backup",
		fi: "Varmuuskopio",
		kn: "Backup",
		es: "Copia de seguridad",
		CN: "保存资料",
		ja: "バックアップの設定",
		fa: "پشتیبان گیری",
		de: "Backup",
		pt: "Cópia de seguran",
		ur: "بیک اپ",
		TW: "儲存資料",
		sv: "Backup",
		ko: "백업",
		nl: "Backup",
		gl: "Copia de seguridade",
		ru: "Резервное сохранение",
	},

	setting_backup_desc : {
		vi: "Lưu lại",
		el: "Αποθηκεύστε τα δεδομένα και τις προσωπικές επιλογές σας",
		fr: "Sauvegarder vos données et modifications",
		en: "save your data and changes",
		sk: "Uložiť dáta a nastavenia",
		cs: "Nastavení zálohování dat",
		pl: "Zachowaj dane i ustawienia",
		it: "salva i tuoi dati e modifiche",
		fi: "tallenna tiedostosi ja tehdyt muutoksesi",
		kn: "save your data and changes",
		es: "Salvaguardar sus datos y modificaciones",
		CN: "保留你的设置和资料",
		ja: "設定と変更を保存",
		fa: "ذخیره کردن تغییرات انجام شده در تاریخ",
		de: "Daten und Einstellungen sichern",
		pt: "Mecanismo persistente",
		ur: "اپنے ڈیٹا اور تبدیلیوں کو محفوظ کریں",
		TW: "保留你的設定和資料",
		sv: "Spara ditt data och inställningar",
		ko: "변경된 내용을 저장합니다",
		nl: "Gegevens en instellingen opslaan",
		gl: "Salvagardar os seus datos e modificacións",
		ru: "Сохранить дату и изменения",
	},

	setting_system : {
		vi: "Hệ thống",
		el: "Σύστημα",
		fr: "Système",
		en: "System",
		sk: "Systém",
		cs: "Systém",
		pl: "System",
		it: "Sistema",
		fi: "Järjestelmä",
		kn: "System",
		es: "Sistema",
		CN: "系统设置",
		ja: "システム設定",
		fa: "سامانه",
		de: "System",
		pt: "Sistema",
		ur: "سسٹم",
		TW: "系統設定",
		sv: "System",
		ko: "시스템",
		nl: "Systeem",
		gl: "Sistema",
		ru: "Система",
	},

	setting_wifi : {
		vi: "WiFi",
		el: "WiFi",
		fr: "WiFi",
		en: "WiFi",
		sk: "WiFi",
		cs: "WiFi",
		pl: "Sieć bezprzewodowa",
		it: "WiFi",
		fi: "WiFi",
		kn: "WiFi",
		es: "WiFi",
		CN: "WiFi",
		ja: "WiFi",
		fa: "WiFi",
		de: "wLAN-Einstellungen",
		ur: "وائی فائی",
		TW: "WiFi",
		sv: "WiFi",
		ko: "WiFi",
		nl: "WiFi",
		gl: "WiFi",
		ru: "WiFi",
	},

	setting_wifi_desc : {
		vi: "Cài đặt sự kết nối không dây",
		el: "Ρυθμίσεις Ασύρματης Σύνδεσης",
		fr: "Configurer la connexion sans fil",
		en: "setup wireless connection",
		sk: "Nastaviť bezdrátové pripojenie k sieti",
		cs: "Nastavení bezdrátového připojení",
		pl: "ustaw połączenia sieci bezprzewodowej",
		it: "configura la connessione senza fili",
		fi: "asenna langaton yhteys",
		kn: "setup wireless connection",
		es: "Configurar la conexión inalámbrica",
		CN: "使用无线网络",
		ja: "無線通信の設定",
		fa: "فراهم کردن ارتباط وایرلس",
		de: "Drahtloses Netzwerk einrichten",
		ur: "وائرلیس کنکشن ترتیب دیں",
		TW: "使用無線網路連線",
		sv: "Konfigurera trådlöst nätverk",
		ko: "무선인터넷을 설정합니다",
		nl: "Draadloze verbinding instellen",
		gl: "Configurar a conexión sen fíos",
		ru: "настроить беспроводное соединение",
	},

	setting_wifi_title : {
		vi: "Cài đặt mạng không dây",
		el: "Ρύθμισεις Ασύρματης Σύνδεσης",
		fr: "Configurer le réseau sans fil",
		en: "Setup Wireless Network",
		sk: "Nastavenie bezdrátovej siete",
		cs: "Nastavení WiFi sítě",
		pl: "Ustawienia sieci bezprzewodowej",
		it: "Imposta la Rete senza fili",
		fi: "Asenna langaton verkko",
		kn: "Setup Wireless Network",
		es: "Configurar la red inalámbrica",
		ja: "無線ネットワークの設定",
		fa: "فراهم کردن شبگه وایرلس",
		de: "Drahtloses Netzwerk Setup",
		ur: "وائیرلیس نیٹ ورک ترتیب دیں",
		TW: "連到無線網路",
		sv: "Konfigurera trådlöst nätverk",
		ko: "무선 네트워크를 설정합니다 ",
		nl: "Draadloos netwerk instellen",
		gl: "Configurar a rede sen fíos",
		ru: "Настроить Беспроводную Сеть",
	},

	setting_wifi_device : {
		vi: "Thiệt bị mạng",
		el: "Συσκευή Δικτύου:",
		fr: "Interface réseau: ",
		en: "Network Device: ",
		sk: "Sieťové zariadenie",
		cs: "Nastavení WiFi zařízení",
		pl: "Urządzenie sieciowe: ",
		it: "Periferica di Rete: ",
		fi: "Verkkolaite: ",
		kn: "Network Device: ",
		es: "Dispositivo inalámbrico: ",
		ja: "ネットワークカード",
		fa: "ابزار شبکه",
		de: "wLAN-Gerät: ",
		ur: "نیٹ ورک آلہ",
		TW: "網路卡: ",
		sv: "Trådlös enhet: ",
		ko: "네트워크 장치",
		nl: "Netwerkapparaat: ",
		gl: "Dispositivo sen fíos",
		ru: "Устройство: ",
	},

	setting_wifi_choose : {
		vi: "Chọn mạng",
		el: "Επιλέξτε Δίκτυο:",
		fr: "Choisissez un réseau: ",
		en: "Choose a network: ",
		sk: "Vyberte si sieť: ",
		cs: "Výběr sítě",
		pl: "Wybierz sieć: ",
		it: "Scegli una rete: ",
		fi: "Valitse verkko: ",
		kn: "Choose a network: ",
		es: "Elija una red: ",
		ja: "ネットワークの選択",
		fa: "انتخاب کردن شبکه",
		de: "Wählen Sie ein Netzwerk",
		pt: "Selecione qual rede você quer se conectar:",
		ur: "نیٹ ورک منتخب کریں",
		TW: "選一個要連線的基地台: ",
		sv: "Välj ett nätverk: ",
		ko: "네트워크를 선택하십시오",
		nl: "Kies een netwerk: ",
		gl: "Elixa unha rede: ",
		ru: "Выберите Сеть: ",
	},

	setting_wifi_refresh : {
		vi: "Làm mới",
		el: "Ανανέωση",
		fr: "Actualiser",
		en: "Refresh",
		sk: "Aktualizovať",
		cs: "Aktualizovat",
		pl: "Odświerz",
		it: "Aggiorna",
		fi: "Päivitä",
		kn: "Refresh",
		es: "Actualizar",
		ja: "リフレッシュ",
		fa: "بازآوری",
		de: "Aktualisieren",
		ur: "تازہ دم کریں",
		TW: "重新整理",
		sv: "Sök",
		ko: "목록 새로 고침",
		nl: "Ververs",
		gl: "Actualizar",
		ru: "Обновить",
	},

	setting_wifi_password : {
		vi: "Mật khẩu",
		el: "Κωδικός",
		fr: "Mot de passe",
		en: "Password:",
		sk: "Heslo:",
		cs: "Heslo",
		pl: "Hasło:",
		fi: "Salasana:",
		kn: "Password:",
		es: "Contraseña",
		ja: "パスワード",
		fa: "کلمه عبور",
		de: "Passwort: ",
		pt: "Senha:",
		ur: "پاس ورڈ",
		TW: "密碼:",
		sv: "Lösenord",
		ko: "암호",
		nl: "Paswoord:",
		gl: "Contrasinal",
		ru: "Пароль:",
	},

	setting_wifi_connect : {
		vi: "Kết nối",
		el: "Σύνδεση",
		fr: "Connecter",
		en: "Connect",
		sk: "Pripojiť sa",
		cs: "Připojit",
		pl: "Połącz",
		it: "Collegati",
		fi: "Yhdistä",
		kn: "Connect",
		es: "Conectar",
		ja: "接続する",
		fa: "برقراری ارتباط",
		de: "Verbinden",
		ur: "کنیکٹ",
		TW: "連線",
		sv: "Anslut",
		ko: "연결",
		nl: "Verbinden",
		gl: "Conectar",
		ru: "Соединить",
	},

	setting_ethernet : {
		vi: "Mạng cục bộ",
		fr: "Connexion filaire",
		en: "Ethernet",
		sk: "Ethernet",
		cs: "Ethernet",
		pl: "Sieć ethernet",
		it: "Ethernet",
		fi: "Lankaverkko",
		kn: "Ethernet",
		es: "Red cableada",
		CN: "有线网络",
		ja: "イーサネット",
		fa: "Ethernet",
		de: "Ethernet",
		ur: "ایتھرنیٹ",
		TW: "有線網路",
		sv: "Ethernet",
		ko: "Ethernet",
		nl: "Ethernet",
		gl: "Rede con fíos",
		ru: "Локальная Сеть",
	},

	setting_ethernet_desc : {
		vi: "Cài đặt kết nối có dây",
		el: "Ρυθμίσεις Ενσύρματης Σύνδεσης",
		fr: "Configurer la connexion filaire",
		en: "setup wired connection",
		sk: "nastavenie káblového pripojenia",
		cs: "Nastavení pevného připojení",
		pl: "ustaw kablowe połączenie sieci ethernet",
		it: "configurare la connessione Internet",
		fi: "asenna lankayhteys",
		kn: "setup wired connection",
		es: "Configurar la conexión cableada",
		CN: "使用有线网络",
		ja: "ケーブル接続の設定",
		fa: "فراهم نمودن ارتباط سیمی",
		de: "Kabelgebundenes Netzwerk einrichten",
		pt: "Configure sua conexão de internet",
		ur: "لوکل ایریا کنکشن ترتیب دیں",
		TW: "連接到網際網路",
		sv: "Konfigurera trådburet nätverk",
		ko: "유선인터넷을 설정합니다",
		nl: "bekabeld netwerk instellen",
		gl: "Configurar a conexión con fíos",
		ru: "настроить проводное соединение",
	},

	setting_opt : {
		vi: "Opt-Get",
		el: "Opt-Get",
		fr: "Opt-Get",
		en: "Opt-Get",
		sk: "Opt-Get",
		cs: "Opt-Get",
		pl: "Opt-Get",
		it: "Opt-Get",
		fi: "Opt-Get",
		kn: "Opt-Get",
		es: "Opt-Get",
		CN: "Opt-Get",
		ja: "Opt-Get",
		fa: "Opt-Get",
		de: "Opt-Get",
		pt: "Opt-Get",
		ur: "Opt-Get",
		TW: "Opt-Get",
		sv: "Opt-Get",
		ko: "Opt-Get",
		nl: "Opt-Get",
		gl: "Opt-Get",
		ru: "Opt-Get",
	},

	setting_opt_desc : {
		vi: "Thêm ứng dụng",
		el: "Εγκατάσταση Πρόσθετων Εφαρμογών",
		fr: "Obtenir plus d'applications",
		en: "get more apps",
		sk: "získajte viac programov",
		cs: "Získání dalších aplikací",
		pl: "pobierz więcej programów",
		it: "ottieni più applicazioni",
		fi: "hae lisää sovelluksia",
		kn: "get more apps",
		es: "Obtener más aplicaciones",
		CN: "安装更多程序",
		ja: "もっと他のアプリケーション",
		fa: "دریافت نرم افزارهای بیشتر",
		de: "Weitere Programme installieren",
		pt: "Baixe mais aplicações",
		ur: "مزید پروگرام حاصل کریں",
		TW: "安裝更多額外程式",
		sv: "Installera flera applikationer",
		ko: "프로그램을 다운로드합니다",
		nl: "Meer toepassingen verkrijgen",
		gl: "Obter máis aplicacións",
		ru: "установить дополнительные программы",
	},

	setting_hardware : {
		vi: "Phần cứng",
		el: "Υλικό",
		fr: "Matériel",
		en: "Hardware",
		sk: "Hardware",
		cs: "Hardware",
		pl: "Sprzęt",
		it: "Hardware",
		fi: "Laitteisto",
		kn: "Hardware",
		es: "Hardware",
		CN: "硬件设置",
		ja: "ハードウェア",
		fa: "سخت افزار",
		de: "Hardware",
		ur: "ھارڈوئیر",
		TW: "硬體設定",
		sv: "Hårdvara",
		ko: "하드웨어",
		nl: "Hardware",
		gl: "Hardware",
		ru: "Оборудование",
	},

	setting_sound : {
		vi: "Âm thanh",
		el: "Ήχος",
		fr: "Son",
		en: "Sound",
		sk: "Zvuk",
		cs: "Zvuk",
		pl: "Dźwięk",
		it: "Audio",
		fi: "Äänet",
		kn: "Sound",
		es: "Sonido",
		CN: "声音",
		ja: "サウンド",
		fa: "صدا",
		de: "Ton",
		pt: "Áudio",
		ur: "آواز",
		TW: "聲音",
		sv: "Ljud",
		ko: "사운드",
		nl: "Geluid",
		gl: "Son",
		ru: "Звук",
	},

	setting_sound_desc : {
		vi: "Điều chỉnh âm thanh",
		el: "Ρύθμιση ήχου",
		fr: "Ajuster les sons système",
		en: "adjust system sound",
		sk: "nastavenia zvuku",
		cs: "Nastavení zvuku",
		pl: "dostosuj ustawienia dźwięku",
		it: "configura le periferiche audio del sistema",
		fi: "Säädä järjestelmän ääniä",
		kn: "adjust system sound",
		es: "Ajustar el sonido del sistema",
		CN: "调整系统音量",
		ja: "システムの音量を設定",
		fa: "مرتب کردن سامانه صدا",
		de: "Systemklänge einstellen",
		pt: "Ajustar som do sistema",
		ur: "سسٹم کی آواز ترتیب دیں",
		TW: "調整系統音量設定",
		sv: "Ändra systemljud",
		ko: "시스템의 사운드를 조절합니다",
		nl: "Geluidsinstellingen",
		gl: "Axustar o son do sistema",
		ru: "настроить звук",
	},

	setting_display : {
		vi: "Hiển thị",
		el: "Οθόνη",
		fr: "Écran",
		en: "Display",
		sk: "Zobrazenie",
		cs: "Zobrazení",
		pl: "Ekran",
		it: "Schermo",
		fi: "Näyttö",
		kn: "Display",
		es: "Pantalla",
		CN: "显示设置",
		ja: "ディスプレイ",
		fa: "نمایشگر",
		de: "Bildschirm",
		pt: "Tela",
		ur: "ڈسپلے",
		TW: "螢幕",
		sv: "Bildskärm",
		ko: "디스플레이",
		nl: "Scherm",
		gl: "Pantalla",
		ru: "Экран",
	},

	setting_display_desc : {
		vi: "Chỉnh độ phân giải",
		el: "Αλλαγή ανάλυσης",
		fr: "Changer la résolution de l'écran",
		en: "change screen resolution",
		sk: "zmena rozlíšenia obrazovky",
		cs: "Nastavení rozlišení obrazovky",
		pl: "zmień ustawienia rozdzielczości",
		it: "cambia la risoluzione dello schermo",
		fi: "muuta näytön tarkkuutta",
		kn: "change screen resolution",
		es: "Cambiar la resolución de la pantalla",
		CN: "调整屏幕分辨率",
		ja: "スクリーンのリゾリューションを変更",
		fa: "تغییر در نحوه نمایش ",
		de: "Auflösung einstellen",
		pt: "Alterar resolução",
		ur: "سکرین کی ریزولوشن تبدیل کریں",
		TW: "調整螢幕解析度",
		sv: "Ändra skärmupplösning",
		ko: "화면 해상도를 조절합니다",
		nl: "Schermresolutie aanpassen",
		gl: "Cambiar a resolución da pantalla",
		ru: "Изменить разрешение экрана",
	},

	setting_driver : {
		vi: "Driver phần cứng",
		el: "Οδηγός",
		fr: "Pilotes",
		en: "Driver",
		sk: "Ovládač",
		cs: "Změna rozlišení obrazovky",
		pl: "Sterownik",
		it: "Driver",
		fi: "Ajuri",
		kn: "Driver",
		es: "Controladores",
		CN: "驱动管理",
		ja: "ドライバ",
		fa: "گرداننده ",
		de: "Treiber",
		ur: "ڈرائیور",
		TW: "裝置管理",
		sv: "Drivrutin",
		ko: "드라이버",
		nl: "Stuurprogramma",
		gl: "Controladores",
		ru: "Устройства",
	},

	setting_driver_desc : {
		vi: "thiết bị và driver phần cứng",
		el: "Πληροφορίες συσκευών και οδηγών",
		fr: "Informations et drivers des périphériques",
		en: "device info and driver",
		sk: "informácie o ovládačoch a zariadeniach",
		cs: "Nastavení ovladačů",
		pl: "informacje o urzączeniu i sterownik",
		it: "informazioni su periferiche e drivers",
		fi: "tietoja laitteista ja ajureista",
		kn: "device info and driver",
		es: "información de los controladores de los periféricos",
		CN: "安装更多驱动程序",
		ja: "デバイス情報とドライバ",
		fa: "ابزار و اطلاعات مربوط به گرداننده ها ",
		de: "Geräteinformationen und Treiber",
		ur: "آلہ کے بارے میں معلومات اور ڈرائیور",
		TW: "安裝更多驅動程式",
		sv: "hårdvaruinformation och drivrutiner",
		ko: "장치정보 및 드라이버",
		nl: "Apparaatinfo en stuurprogramma",
		gl: "Información dos controladores dos periféricos",
		ru: "информация об устройствах и драйверах",
	},

	setting_sysinfo : {
		el: "Πληροφορίες Συστήματος",
		fr: "Informations système",
		en: "System Info",
		sk: "Systémové informácie",
		cs: "Systémové informace",
		kn: "System Info",
		fa: "اطلاعات سامانه ",
		de: "Systeminformation",
		TW: "系統資訊",
		ko: "시스템 정보",
		nl: "Systeem Info",
	},

	setting_sysinfo_desc : {
		el: "Έλεγχος Συστήματος",
		fr: "Vérifier les informations système",
		en: "check system information",
		sk: "zobraziť systémove informácie",
		cs: "Zobrazení systémových informací",
		kn: "check system information",
		fa: "بررسی اطلاعات سامانه ",
		de: "Übersicht über Gesamtsystem",
		TW: "檢視系統狀態",
		ko: "시스템 정보를 확인합니다",
		nl: "controleer systeem info",
	},

	back_to_setting : {
		vi: "Quay lại Tùy chọn",
		el: "Επιστροφή στις Επιλογές",
		fr: "Retour aux Paramètres",
		en: "Back to Settings",
		sk: "Späť do nastavení",
		cs: "Zpět do nastavení",
		pl: "Wróć do ustawień",
		it: "Torna alle Impostazioni",
		fi: "Takaisin asetuksiin",
		kn: "Back to Settings",
		es: "Volver a Configuración",
		CN: "返回设置",
		ja: "設定に戻る",
		fa: "بازگشت به قسمت مشخصه ها ",
		de: "Zurück zu den Einstellungen",
		ur: "واپس سیٹنگز پر",
		TW: "回到設定頁面",
		sv: "Tillbaka till Inställningar",
		ko: "이전 화면으로",
		nl: "Terug naar instellingen",
		gl: "Volver a Configuración",
		ru: "Назад к Настройкам",
	},

}