// Plate UI translation file

var i18n =  {

// tab 

    home : {
		en: "Home",
		de: "Start",
		es: "Inicio",
		fr: "Accueil",
		it: "Home",
		jp: "ホーム",
		pt: "P&#225;gina Inicial",
		se: "Hem",
		zh: "回到主頁",
		zh_cn: "首页",
    },
    
    menu : {
		en: "Menu",
		de: "Programme",
		es: "Men&uacute;",
		fr: "Menu",
		it: "Menu",
		jp: "メニュー",
		pt: "Menu",
		se: "Meny",
		zh: "執行程式",
		zh_cn:"应用程序",
    },

    file : {
		en: "File",
		de: "Dateien",
		es: "Archivos",
		fr: "Fichier",
		it: "File",
		jp: "ファイル",
		pt: "Arquivos",
		se: "Filer",
		zh: "開啟檔案",
		zh_cn:"打开文件",
    },

    setting : {
		en: "Setting",
		de: "Einstellung",
		es: "Preferencias",
		fr: "Préférences",
		it: "Preferenze",
		jp: "セッティング",
		pt: "Configura&#231;&#245;es",
		se: "Inställning",
		zh: "設定系統",
		zh_cn: "设置系统",
    },
    
// home 

    welcome : {
		en: "Welcome to xPUD",
		de: "Willkommen bei xPUD",
		es: "Bienvenido a xPUD",
		fr: "Bienvenue sur xPUD",
		it: "Benvenuto in xPUD",
		jp: "xPUDに　ようこそ",
		pt: "Bem vindo ao xPUD",
		se: "Välkommen till xPUD",
		zh: "歡迎使用 xPUD",
		zh_cn: "欢迎使用 xPUD",
    },
    
	sys_info: {
		en: "System Information",
		de: "Systeminformationen",
		es: "Informaci&oacute;n del sistema",
		fr: "Informations du système",
		it: "Informazioni di Sistema",
		jp: "システム情報",
		pt: "Informa&#231;&#245;es do sistema",
		se: "Systeminformation",
		zh: "系統資訊",
		zh_cn: "系统信息",
	},

	want_to: {
		en: "You may want to:",
		de: "Sie k&ouml;nnen:",
		es: "Quiz&aacute;s desee:",
		fr: "Vous voulez:",
		it: "Forse volete:",
		jp: "次のアクションもできます",
		pt: "Talvez voc&#234; deseja:",
		se: "Du kanske vill:",
		zh: "你也可以：",
		zh_cn:"你也可以：",
	},
	
	power_off: {
		en: "Power Off",
		de: "Ausschalten",
		es: "Apagar",
		fr: "Éteindre",
		it: "Arresto",
		jp: "電源を切る",
		pt: "Desligar",
		se: "Stänga av",
		zh: "關機",
		zh_cn:"关机",
	},
	
		quit_now: {
			en: "Do you want to quit now?",
			de: "M&ouml;chten Sie jetzt ausschalten?",
			fr: "Voulez-vous quitter maintenant ?",
			it: "Vuoi uscire adesso?",
			jp: "終了しますか？",
			pt: "Voc&#234; deseja sair agora?",
			se: "Vill du avsluta nu?",
			zh: "確定要關機?",
			zh_cn: "确定要关机?",
		},
	
		turn_off: {
			en: "Turn Off",
			de: "Ausschalten",
			fr: "Éteindre",
			it: "Spegni",
			jp: "終了",
			pt: "Desligar",
			se: "Stäng av",
			zh: "關機",
			zh_cn: "关机",
		},
	
		restart: {
			en: "Restart",
			de: "Neustart",
			fr: "Redémarrer",
			it: "Riavvia",
			jp: "再起動",
			pt: "Reiniciar",
			se: "Starta om",
			zh: "重新開機",
			zh_cn: "重启",
		},
		
		cancel_shutdown: {
			en: "Cancel",
			de: "Abbrechen",
			fr: "Abandonner",
			it: "Annulla",
			jp: "キャンセル",
			pt: "Cancelar",
			se: "Avbryt",
			zh: "取消",
			zh_cn:"取消",
		},
	
	power_off_desc: {
		en: "turn off this machine",
		de: "Dieses Ger&auml;t ausschalten",
		es: "Apagar su equipo",
		fr: "Éteindre l'ordinateur",
		it: "Spegni il computer",
		jp: "PCの電源を切る",
		pt: "Desligar computador",
		se: "Stäng av denna dator",
		zh: "關閉這台電腦",
		zh_cn:"关闭这台电脑",
	},
	switch_mode: {
		en: "Switch Mode",
		de: "System wechseln",
		es: "Cambiar SO",
		fr: "Changer de mode",
		it: "Cambia Sistema",
		jp: "モードを切換える",
		se: "Ändra läge",
		zh: "切換模式",
		zh_cn:"切换模式",
	},
	switch_mode_desc: {
		en: "toggle into other OS",
		de: "Anderes Betriebssystem starten",
		es: "Cambiar a otro Sistema Operativo",
		fr: "Basculer dans un autre OS",
		it: "Passa ad un altro Sistema Operativo",
		jp: "別のOSに切換える",
		se: "Starta andra operativsystem",
		zh: "使用其他作業系統",
		zh_cn:"使用其他操作系統",
	},
	get_help: {
		en: "Get Help",
		de: "Hilfe",
		es: "Obtener Ayuda",
		fr: "Obtenir de l'aide",
		it: "Ottenere Aiuto",
		jp: "ヘルプしてもらう",
		pt: "Obter ajuda",
		se: "Hjälp",
		zh: "取得幫助",
		zh_cn:"获取帮助",
	},
	
	get_help_desc: {
		en: "and contact information",
		de: "und Kontaktinformationen",
		es: "e informaci&oacute;n de contacto",
		fr: "information et contact",
		it: "e informazioni/contatti",
		jp: "その後xPUDの情報を見る",
		pt: "Aprender mais sobre o xPUD",
		se: "och kontaktinformation",
		zh: "和更多資訊",
		zh_cn:"了解xPUD的更多信息",
	},
	
		help_about: {
			en: "About",
			de: "&Uuml;ber",
			fr: "À propos de",
			it: "Informazioni",
			jp: "xPUDについて",
			se: "Om",
			zh: "更多訊息",
			zh_cn:"关于xPUD计划",
		},
		help_info: {
			en: "xPUD is a rapidly developing project. <br /> For more information, please go to:",
			de: "xPUD ist ein aktiv entwickeltes Projekt. <br /> Weitere Informationen unter:",
			fr: "xPUD est un projet qui se développe rapidement. <br /> Pour plus d'informations, visitez :",
			it: "xPUD &egrave; un progetto in rapida evoluzione. <br /> Per maggiori informazioni, per favore visita: ",
			jp: "xPUDは開発速度の早いプロジェクトです。<br /> もっと情報が必要でしたら、次にお進みください：",
			se: "xPUD är ett snabbt utvecklande projekt. <br /> För mer information, gå till:",
			zh: "xPUD 是一個快速發展中的計畫。請參閱：",
			zh_cn:"xPUD 是一个快速发展中的计划。请参阅：",
		},
		help_done: {
			en: "Done",
			de: "OK",
			fr: "OK",
			it: "OK",
			jp: "完成です",
			se: "Klar",
			zh: "完成",
			zh_cn:"完成",
		},
// menu
	application: {
		en: "Applications",
		de: "Programme",
		es: "Aplicaciones",
		fr: "Applications",
		it: "Applicazioni",
		jp: "アプリケーション",
		pt: "Aplica&#231;&#245;es",
		se: "Applikationer",
		zh: "所有應用程式",
		zh_cn:"所有应用程序",
	},
	
	web_browser: {
		en: "Web Browser",
		de: "Web Browser",
		es: "Navegador web",
		fr: "Navigateur Web",
		it: "Browser Web",
		jp: "ウェブブラウザ",
		pt: "Navegador de internet",
		se: "Webbläsare",
		zh: "網頁瀏覽器",
		zh_cn:"上网冲浪",
	},
	bt_client: {
		en: "BitTorrent Client",
		de: "BitTorrent Client",
		es: "Cliente BitTorrent",
		fr: "Client BitTorrent",
		it: "Client BitTorrent",
		jp: "ビットトレント",
		pt: "Cliente BitTorrent",
		se: "BitTorrent Klient",
		zh: "BT 下載",
		zh_cn:"BT 下载",
	},
	media_player: {
		en: "Media Player",
		de: "Media Player",
		es: "Reproductor Multimedia",
		fr: "Lecteur Multimedia",
		it: "Lettore Multimediale",
		jp: "メディアプレーヤ",
		pt: "Reprodutor multim&#233;dia",
		se: "Mediaspelare",
		zh: "影音播放",
		zh_cn:"播放影音",
	},
	picture_viewer: {
		en: "Picture Viewer",
		de: "Bildbetrachter",
		es: "Visor de im&aacute;genes",
		fr: "Visionneur d'images",
		it: "Visualizzatore di Immagini",
		jp: "ピクチャービューア",
		pt: "Visualizador de imagens",
		se: "Bildvisare",
		zh: "圖片瀏覽",
		zh_cn:"浏览图片",
	},
	text_editor: {
		en: "Text Editor",
		de: "Text Editor",
		es: "Editor de textos",
		fr: "Éditeur de texte",
		it: "Editor di Testo",
		jp: "テキストエディタ",
		pt: "Editor de texto",
		se: "Textredigerare",
		zh: "文字編輯",
		zh_cn:"编辑文字",
	},
	pdf_viewer: {
		en: "PDF Viewer",
		de: "PDF Viewer",
		es: "Visor de PDF",
		fr: "Visionneur de PDF",
		it: "Visualizzatore di PDF",
		jp: "PDFビューア",
		pt: "Visualizador de PDFs",
		se: "PDF läsare",
		zh: "PDF 閱讀",
		zh_cn:"阅读PDF",
	},
	terminal_emulator: {
		en: "Terminal Emulator",
		de: "Terminal Emulator",
		es: "Emulador de terminal",
		fr: "Émulateur de terminal",
		it: "Emulatore di Teminale",
		jp: "ターミナル　エミュレータ",
		pt: "Terminal",
		se: "Kommandotolk",
		zh: "終端機",
		zh_cn:"使用终端",
	},
	
// setting

	setting_personal: {
		en: "Personal",
		de: "Pers&ouml;nliche Einstellungen",
		es: "Personal",
		fr: "Personnel",
		it: "Personale",
		jp: "個人設定",
		se: "Personliga inställningar",
		zh: "個人設定",
		zh_cn:"个人设置",
	},
	
		setting_language: {
			en: "Language",
			de: "Sprache",
			es: "Idioma",
			fr: "Langue",
			it: "Lingua",
			jp: "言語の選択",
			se: "Språk",
			zh: "語言選項",
			zh_cn:"语言选项",
		},
		setting_language_desc: {
			en: "choose locale and keymap",
			de: "sprache und tastenbelegung",
			es: "elegir el idioma y la distribuci&oacute;n del teclado",
			fr: "choisir la langue et la disposition du clavier",
			it: "scegli la lingua e la configurazione della tastiera",
			jp: "ローカライズとキーの切換",
			se: "språk- och tangentbordsinstälnningar",
			zh: "切換語系和鍵盤",
			zh_cn:"切换语系和键盘",
		}, 
	
		setting_time_date: {
			en: "Time & Date",
			de: "Datum und Uhrzeit",
			es: "Fecha y hora",
			fr: "Date et heure",
			it: "Data e Ora",
			jp: "時間と月日",
			pt: "Relógio",
			se: "Tid och Datum",
			zh: "時間日期",
			zh_cn:"时间与日期",
		},
		setting_time_date_desc: {
			en: "change system clock",
			de: "Systemuhr einstellen",
			es: "cambiar la hora del sistema",
			fr: "Changer l'heure du système",
			it: "Cambia l'ora di Sistema",
			jp: "システムの日時を変更",
			pt: "Atualize o rel&#243;gio do sistema",
			se: "ändra systemtid",
			zh: "調整系統日期與時間",
			zh_cn:"调整系统的日期与时间",
		},
		setting_backup: {
			en: "Backup",
			de: "Backup",
			es: "Copia de Seguridad",
			fr: "Sauvegarde",
			it: "Copia di Backup",
			jp: "バックアップの設定",
			pt: "C&#243;pia de seguran",
			se: "Backup",
			zh: "儲存資料",
			zh_cn:"保存资料",
		},
		setting_backup_desc: {
			en: "save your data and changes",
			de: "Daten und Einstellungen sichern",
			es: "salvar sus datos y modificaciones",
			fr: "Sauver vos données et modifications",
			it: "salva i tuoi dati e modifiche",
			jp: "設定と変更を保存",
			pt: "Mecanismo persistente",
			se: "Spara ditt data och inställningar",
			zh: "保留你的設定和資料",
			zh_cn:"保留你的设置和资料",
		},


	setting_system: {
		en: "System",
		de: "System",
		es: "Sistema",
		fr: "Système",
		it: "Sistema",
		jp: "システム設定",
		pt: "Sistema",
		se: "System",
		zh: "系統設定",
		zh_cn:"系统设置",
	},
	
		setting_wifi: {
			en: "WiFi",
			de: "WiFi",
			es: "WiFi",
			fr: "WiFi",
			it: "WiFi",
			jp: "WiFi",
			se: "WiFi",
			zh: "WiFi",
			zh_cn:"WiFi",
		},
		setting_wifi_desc: {
			en: "setup wireless connection",
			de: "drahtloses netzwerk einrichten",
			es: "configurar la conexi&oacute;n inal&aacute;mbrica",
			fr: "configurer la connexion sans fil",
			it: "configura la connessione senza fili",
			jp: "無線通信の設定",
			se: "Konfigurera trådlöst nätverk",
			zh: "使用無線網路連線",
			zh_cn:"使用无线网络",
		},
			setting_wifi_title: {
				en: "Setup Wireless Network",
				de: "Drahtloses Netzwerk Setup",
				fr: "configurer le réseau sans fil",
				it: "Imposta la Rete senza fili",
				jp: "無線ネットワークの設定",
				se: "Konfigurera trådlöst nätverk",
				zh: "連到無線網路",
			},
			setting_wifi_device: {
				en: "Network Device: ",
				de: "WiFi Netzwerk Ger&auml;t: ",
				fr: "Interface réseau: ",
				it: "Periferica di Rete: ",
				jp: "ネットワークカード",
				se: "Trådlös enhet: ",
				zh: "網路卡: ",
			},
			setting_wifi_choose: {
				en: "Choose a network: ",
				de: "W&auml;le ein Netzwerk",
				fr: "Choisissez un réseau: ",
				it: "Scegli una rete: ",
				jp: "ネットワークの選択",
				pt: "Selecione qual rede você quer se conectar:",
				se: "Välj ett nätverk: ",
				zh: "選一個要連線的基地台: ",
			},
			setting_wifi_refresh: {
				en: "Refresh",
				de: "Aktualisieren",
				fr: "Actualiser",
				it: "Aggiorna",
				jp: "リフレッシュ",
				se: "Sök",
				zh: "重新整理",
			},
			setting_wifi_password: {
				en: "Password:",
				de: "Passwort:",
				fr: "Mot de passe",
				jp: "パスワード",
				pt: "Senha:",
				se: "Lösenord",
				zh: "密碼:",
			},
			setting_wifi_connect: {
				en: "Connect",
				de: "Verbinden",
				fr: "Connecter",
				it: "Collegati",
				jp: "接続する",
				se: "Anslut",
				zh: "連線",
			},
		setting_ethernet: {
			en: "Ethernet",
			de: "Ethernet",
			es: "Red Cableada",
			fr: "Connexion filaire",
			it: "Ethernet",
			jp: "イーサネット",
			se: "Ethernet",
			zh: "有線網路",
			zh_cn:"有线网络",
		},
		setting_ethernet_desc: {
			en: "setup wired connection",
			de: "kabelgebundenes netzwerk einrichten",
			es: "configurar la conexi&oacute;n cableada",
			fr: "configurer la connexion filaire",
			it: "configurare la connessione Internet",
			jp: "ケーブル接続の設定",
			pt: "Configure sua conex&#227;o de internet",
			se: "Konfigurera trådburet nätverk",
			zh: "連接到網際網路",
			zh_cn:"使用有线网络",
		},
		setting_opt: {
			en: "Opt-Get",
			de: "Opt-Get",
			es: "Opt-Get",
			fr: "Opt-Get",
			it: "Opt-Get",
			jp: "Opt-Get",
			pt: "Opt-Get",
			se: "Opt-Get",
			zh: "Opt-Get",
			zh_cn:"Opt-Get",
		},
		setting_opt_desc: {
			en: "get more apps",
			de: "weitere programme installieren",
			es: "obtener m&aacute;s aplicaciones",
			fr: "obtenir plus d'applications",
			it: "ottieni pi&ugrave; applicazioni",
			jp: "もっと他のアプリケーション",
			pt: "Baixe mais aplica&#231;&#245;es",
			se: "Installera flera applikationer",
			zh: "安裝更多額外程式",
			zh_cn:"安装更多程序",
		},
	
	setting_hardware: {
		en: "Hardware",
		de: "Hardware",
		es: "Hardware",
		fr: "Matériel",
		it: "Hardware",
		jp: "ハードウェア",
		se: "Hårdvara",
		zh: "硬體設定",
		zh_cn:"硬件设置",
	},
		setting_sound: {
			en: "Sound",
			de: "Ton",
			es: "Sonido",
			fr: "Son",
			it: "Audio",
			jp: "サウンド",
			pt: "&#193;udio",
			se: "Ljud",
			zh: "聲音",
			zh_cn:"声音",
		},
		setting_sound_desc: {
			en: "adjust system sound",
			de: "Systemkl&auml;nge einstellen",
			es: "ajustar el sonido del sistema",
			fr: "ajuster les sons système",
			it: "configura le periferiche audio del sistema",
			jp: "システムの音量を設定",
			pt: "Ajustar som do sistema",
			se: "Ändra systemljud",
			zh: "調整系統音量設定",
			zh_cn:"调整系统音量",
		},
		setting_display: {
			en: "Display",
			de: "Bildschirm",
			es: "Pantalla",
			fr: "Écran",
			it: "Schermo",
			jp: "ディスプレイ",
			pt: "Tela",
			se: "Bildskärm",
			zh: "螢幕",
			zh_cn:"显示设置",
		},
		setting_display_desc: {
			en: "change screen resolution",
			de: "Aufl&ouml;sung einstellen",
			es: "cambiar la resoluci&oacute;n de la pantalla",
			fr: "changer la résolution de l'écran",
			it: "cambia la risoluzione dello schermo",
			jp: "スクリーンのリゾリューションを変更",
			pt: "Alterar resolu&#231;&#227;o",
			se: "Ändra skärmupplösning",
			zh: "調整螢幕解析度",
			zh_cn:"调整屏幕分辨率",
		},
		setting_driver: {
			en: "Driver",
			de: "Treiber",
			es: "Controladores",
			fr: "Pilotes",
			it: "Driver",
			jp: "ドライバ",
			se: "Drivrutin",
			zh: "裝置管理",
			zh_cn:"驱动管理",
		},
		setting_driver_desc: {
			en: "device info and driver",
			de: "ger&auml;teinformationen und treiber",
			es: "informaci&oacute;n de los controladores de los perif&eacute;ricos",
			fr: "informations et drivers des périphériques",
			it: "informazioni su periferiche e drivers",
			jp: "デバイス情報とドライバ",
			se: "hårdvaruinformation och drivrutiner",
			zh: "安裝更多驅動程式",
			zh_cn:"安装更多驱动程序",
		},
		
			back_to_setting: {
				en: "Back to Setting",
				de: "Zur&uuml;ck zu den Einstellungen",
				fr: "Retour aux Paramètres",
				it: "Torna alle Impostazioni",
				jp: "設定に戻る",
				se: "Tillbaka till Inställningar",
				zh: "回到設定頁面",
				zh_cn: "返回设置",
		},

};

