// Plate UI translation file

var i18n =	{

// tab

	home : {
		en: "Home",
		de: "Start",
		es: "Inicio",
		fi: "Käynnistä",
		fr: "Accueil",
		gl: "Inicio",
		it: "Home",
		jp: "ホーム",
		pt: "P&#225;gina Inicial",
		se: "Hem",
		zh: "回到主頁",
		zh_cn: "首页",
		ru: "Главная страница",
		pl: "Start",
		vn: "Khởi động",
		el: "Αρχική Σελίδα",
		ur: "صفحہ اول",
		cs: "Start",
		nl:"Start",
		fa: "خانه",
		kr: "시작",
	},

	menu : {
		en: "Menu",
		de: "Programme",
		es: "Men&uacute;",
		fi: "Valikko",
		fr: "Menu",
		gl: "Men&uacute;",
		it: "Menu",
		jp: "メニュー",
		pt: "Menu",
		se: "Meny",
		zh: "執行程式",
		zh_cn:"应用程序",
		ru: "Программы",
		pl: "Menu",
		vn: "Trình đơn",
		el: "Μενού",
		ur: "فہرست",
		cs: "Menu",
	   	nl:"Menu",
		fa: "فهرست",
		kr: "메뉴",
	},

	file : {
		en: "File",
		de: "Dateien",
		es: "Archivos",
		fi: "Tiedosto",
		fr: "Fichier",
		gl: "Ficheiros",
		it: "File",
		jp: "ファイル",
		pt: "Arquivos",
		se: "Filer",
		zh: "開啟檔案",
		zh_cn:"打开文件",
		ru: "Файл",
		pl: "Plik",
		vn: "Tập tin",
		el: "Αρχεία",
		ur: "فائل",
		cs: "Soubor",
		nl:"Bestanden",
		fa: "فایل",
		kr: "파일",
	},

	setting : {
		en: "Settings",
		de: "Einstellung",
		es: "Preferencias",
		fi: "Asetukset",
		fr: "Préférences",
		gl: "Preferencias",
		it: "Preferenze",
		jp: "セッティング",
		pt: "Configura&#231;&#245;es",
		se: "Inställning",
		zh: "設定系統",
		zh_cn: "设置系统",
		ru: "Настройки",
		pl: "Ustawienia",
		vn: "Tùy chọn",
		el: "Επιλογές",
		ur: "ترکیب",
		cs: "Nastavení",
		nl:"Instellingen",
		fa: "مشخصه ها",
		kr: "설정",
	},

// home 

	welcome : {
		en: "Welcome to xPUD",
		de: "Willkommen bei xPUD",
		es: "Bienvenido a xPUD",
		fi: "Tervetuloa xPUD:iin",
		fr: "Bienvenue sur xPUD",
		gl: "Benvido a xPUD",
		it: "Benvenuto in xPUD",
		jp: "xPUDに　ようこそ",
		pt: "Bem vindo ao xPUD",
		se: "Välkommen till xPUD",
		zh: "歡迎使用 xPUD",
		zh_cn: "欢迎使用 xPUD",
		ru: "Добро пожаловать в xPUD",
		pl: "Witaj w xPUD",
		vn: "Chào mừng bạn đến với xPUD",
		el: "Καλώς ορίσατε στο xPUD",
		ur: "میں خوش آمدید xPUD",
		cs: "Vítej v xPUD",
		nl:"Welkom bij xPUD",
		fa: "خوش آمدید",
		kr: "xPUD에 오신 것을 환영합니다",
	},

	sys_info: {
		en: "System Information",
		de: "Systeminformationen",
		es: "Informaci&oacute;n del sistema",
		fi: "Järjestelmätiedot",
		fr: "Informations du système",
		gl: "Informaci&oacute;n do sistema",
		it: "Informazioni di Sistema",
		jp: "システム情報",
		pt: "Informa&#231;&#245;es do sistema",
		se: "Systeminformation",
		zh: "系統資訊",
		zh_cn: "系统信息",
		ru: "Системная Информация",
		pl: "Informacje o systemie",
		vn: "Thông tin hệ thống",
		el: "Πληροφορίες Συστήματος",
		ur: "سسٹم کے بارے میں معلومات",
		cs: "Systémové Informace",
		nl:"Systeeminformatie",
		fa: "اطلاعات سامانه",
		kr: "시스템 정보",
	},

	want_to: {
		en: "You may want to:",
		de: "Sie k&ouml;nnen:",
		es: "Quiz&aacute;s desee:",
		gl: "Cecais desexe:",
		fi: "Haluatko:",
		fr: "Vous voulez:",
		it: "Forse volete:",
		jp: "次のアクションもできます",
		pt: "Talvez voc&#234; deseja:",
		se: "Du kanske vill:",
		zh: "你也可以：",
		zh_cn:"你也可以：",
		ru: "Желаете:",
		pl: "Co chcesz zrobić?",
		vn: "Bạn có muốn tới",
		el: "Θελετε να:",
		ur: "اگر آپ چاہیں",
		cs: "Co chceš udělat:",
		nl:"wilt u:",
		fa: "شما ممکن است درخواست کنید که:",
		kr: "이런 것도 할 수 있습니다",
	},

	quick_action: {
		en: "Quick Action",
		zh: "快速選單",
		nl:"Snelkeuze",
		fa: "عملیات سریع",
		kr: "빠른 실행",
	},

	power_off: {
		en: "Power Off",
		de: "Ausschalten",
		es: "Apagar",
		fi: "Sammuta",
		fr: "Éteindre",
		gl: "Apagar",
		it: "Arresto",
		jp: "電源を切る",
		pt: "Desligar",
		se: "Stänga av",
		zh: "關機",
		zh_cn:"关机",
		ru: "Выключить",
		pl: "Wyłącz",
		vn: "Tắt máy",
		el: "Τερματισμός",
		ur: "پاور آف",
		cs: "Vypnout",
		nl:"Uitschakelen",
		fa: "خارج شدن",
		kr: "종료",
	},

	quit_now: {
		en: "Do you want to quit now?",
		de: "M&ouml;chten Sie jetzt ausschalten?",
		es: "¿Desea Usted salir ahora?",
		fi: "Haluatko lopetaa nyt?",
		fr: "Voulez-vous quitter maintenant ?",
		gl: "Desexa vostede sa&iacute;r agora?",
		it: "Vuoi uscire adesso?",
		jp: "終了しますか？",
		pt: "Voc&#234; deseja sair agora?",
		se: "Vill du avsluta nu?",
		zh: "確定要關機?",
		zh_cn: "确定要关机?",
		ru: "Действительно выйти?",
		pl: "Jesteś pewien że chcesz zakończyć?",
		vn: "Bạn có muốn thoát ra bây giờ không",
		el: "Άμεσος τερματισμός;",
		ur: "پاور آف",
		cs: "Opravdu ukončit?",
		nl:"Wilt u nu afsluiten ?",
		fa: "آیا تصمیم دارید خارج شوید؟",
		kr: "지금 종료하시겠습니까?",
	},

		turn_off: {
			en: "Turn Off",
			de: "Ausschalten",
			es: "Apagar",
			fi: "Sammuta",
			fr: "Éteindre",
			gl: "Apagar",
			it: "Spegni",
			jp: "終了",
			pt: "Desligar",
			se: "Stäng av",
			zh: "關機",
			zh_cn: "关机",
			ru: "Выключить",
			pl: "Wyłącz",
			vn: "Tắt máy",
			el: "Τερματισμός",
			ur: "بند کر دیں",
			cs: "Vypnout",
			nl:"Afsluiten",
			fa: "خاموش کردن",
			kr: "종료",
		},

		restart: {
			en: "Restart",
			de: "Neustart",
			es: "Reiniciar",
			fi: "Käynnistä uudelleen",
			fr: "Redémarrer",
			gl: "Reiniciar",
			it: "Riavvia",
			jp: "再起動",
			pt: "Reiniciar",
			se: "Starta om",
			zh: "重新開機",
			zh_cn: "重启",
			ru: "Перезагрузить",
			pl: "Uruchom ponownie",
			vn: "Khởi động lại",
			el: "Επανεκκίνηση",
			ur: "دوبارہ چلائیں",
			cs: "Restartovat",
			nl:"Herstarten",
			fa: "باز آوری",
			kr: "다시 시작",
		},

		cancel_shutdown: {
			en: "Cancel",
			de: "Abbrechen",
			es: "Cancelar",
			fi: "Peruuta",
			fr: "Abandonner",
			gl: "Cancelar",
			it: "Annulla",
			jp: "キャンセル",
			pt: "Cancelar",
			se: "Avbryt",
			zh: "取消",
			zh_cn:"取消",
			ru: "Отменить",
			pl: "Anuluj",
			vn: "Thôi",
			el: "Ακύρωση",
			ur: "کینسل",
			cs: "Zrušit",
			nl:"Annuleren",
			fa: "لغو کردن",
			kr: "취소",
		},

		save_backup_to: {
			en: "Save backup to",
			zh: "保留設定至",
			fr: "Sauvergarder sur",
			cs: "Rychlá akce",
			nl:"Backup opslaan in",
			fa: "ذخیره کردن پشتیبان",
			kr: "지정 디스크에 백업",
		},

	power_off_desc: {
		en: "turn off this machine",
		de: "Dieses Ger&auml;t ausschalten",
		es: "Apagar su equipo",
		fi: "Sammuta tietokone",
		fr: "Éteindre l'ordinateur",
		gl: "Apagar o seu equipo",
		it: "Spegni il computer",
		jp: "PCの電源を切る",
		pt: "Desligar computador",
		se: "Stäng av denna dator",
		zh: "關閉這台電腦",
		zh_cn:"关闭这台电脑",
		ru: "Выключить компьютер",
		pl: "Wyłącz ten komputer",
		vn: "Tắt máy tính này",
		el: "Τερματισμός Λειτουργίας",
		ur: "اس میشین کو بند کردیں",
		fa: "خاموش کردن سامانه",
		cs: "Vypnout počítač",
		nl:"Computer afsluiten",
		kr: "컴퓨터를 종료합니다",
		
	},

	switch_mode: {
		en: "Switch Mode",
		de: "System wechseln",
		es: "Cambiar de SO",
		fi: "Vaihda tila",
		fr: "Changer de mode",
		gl: "Cambiar de SO",
		it: "Cambia Sistema",
		jp: "モードを切換える",
		se: "Ändra läge",
		zh: "切換模式",
		zh_cn:"切换模式",
		ru: "Переключить режим",
		pl: "Przełącz między systemami",
		vn: "Chuyển tài khoản",
		el: "Αλλαγή Λειτουργικού",
		ur: "سسٹم تبدیلی",
		cs: "Změnit systém",
		nl:"Systeem wisselen",
		fa: "تغییر روش",
		kr: "시스템 전환",
	},

	switch_mode_desc: {
		en: "toggle into other OS",
		de: "Anderes Betriebssystem starten",
		es: "Cambiar a otro sistema operativo",
		fi: "Vaihda toiseen käyttöjärjestelmään",
		fr: "Basculer dans un autre OS",
		gl: "Cambiar a outro sistema operativo",
		it: "Passa ad un altro Sistema Operativo",
		jp: "別のOSに切換える",
		se: "Starta andra operativsystem",
		zh: "使用其他作業系統",
		zh_cn:"使用其他操作系統",
		ru: "загрузить другую ОС",
		pl: "przełącz do innego SO",
		vn: "Sang hệ điều hành khác",
		el: "Εναλλαγή Λειτουργικού Συστήματος",
		ur: "دوسرے آپریٹنگ سسٹم میں تبدیلی",
		cs: "Spustit jiný operační sytém",
		nl:"Ander OS kiezen",
		fa: "رفتن به سیستم عامل دیگر",
		kr: "다른 운영체제로 전환합니다",
	},

	get_help: {
		en: "Get Help",
		de: "Hilfe",
		es: "Obtener ayuda",
		fi: "Ohjeet",
		fr: "Obtenir de l'aide",
		gl: "Obter axuda",
		it: "Ottenere Aiuto",
		jp: "ヘルプしてもらう",
		pt: "Obter ajuda",
		se: "Hjälp",
		zh: "取得幫助",
		zh_cn:"获取帮助",
		ru: "Помощь",
		pl: "Pomoc",
		vn: "Trợ giúp",
		el: "Βοήθεια",
		ur: "مدد حاصل کریں",
		cs: "Nápověda",
		nl:"hulp vragen",
		fa: "درخواست کمک",
		kr: "도움말",
	},

	get_help_desc: {
		en: "and contact information",
		de: "und Kontaktinformationen",
		es: "e informaci&oacute;n de contacto",
		fi: "ja yhteystiedot",
		fr: "information et contact",
		gl: "e informaci&oacute;n de contacto",
		it: "e informazioni/contatti",
		jp: "その後xPUDの情報を見る",
		pt: "Aprender mais sobre o xPUD",
		se: "och kontaktinformation",
		zh: "和更多資訊",
		zh_cn:"了解xPUD的更多信息",
		ru: "и контакты",
		pl: "i informacje kontaktowe",
		vn: "và thông tin liên lạc",
		el: "και επικοινωνία",
		ur: "اور رابطہ کیلئے معلومات",
		cs: "a kontaktní informace",
		nl:"en contact informatie",
		fa: "برقرای ارتباط",
		kr: "와(과) 연락 정보",
	},

	help_about: {
		en: "About",
		de: "&Uuml;ber",
		es: "Acerca de",
		fi: "Tietoja",
		fr: "À propos de",
		gl: "Acerca de",
		it: "Informazioni",
		jp: "xPUDについて",
		se: "Om",
		zh: "更多訊息",
		zh_cn:"关于xPUD计划",
		ru: "О",
		pl: "O...",
		vn: "Giới thiệu",
		el: "Σχετικά με το xPUD",
		ur: "کے بارے میں",
		cs: "O...",
		nl:"Info",	
		fa: "درباره سامانه",
		kr: "xPUD에 대해서",
	},

		help_info: {
		en: "xPUD is a rapidly developing project. <br /> For more information, please go to:",
		de: "xPUD ist ein aktiv entwickeltes Projekt. <br /> Weitere Informationen unter:",
		es: "XPUD es un proyecto con un desarrollo muy r&aacute;pido <br /> Para m&aacute;s informaci&oacute;n visite:",
		fi: "xPUD kehittyy nopeasti. <br /> Lisätietoja saat osoitteesta:",
		fr: "xPUD est un projet qui se développe rapidement. <br /> Pour plus d'informations, visitez :",
		gl: "XPUD &eacute; un proxecto con un desenvolvemento moi r&aacute;pido <br /> Para m&aacute;is informaci&oacute;n visite:",
		it: "xPUD &egrave; un progetto in rapida evoluzione. <br /> Per maggiori informazioni, per favore visita: ",
		jp: "xPUDは開発速度の早いプロジェクトです。<br /> もっと情報が必要でしたら、次にお進みください：",
		se: "xPUD är ett snabbt utvecklande projekt. <br /> För mer information, gå till:",
		zh: "xPUD 是一個快速發展中的計畫。請參閱：",
		zh_cn:"xPUD 是一个快速发展中的计划。请参阅：",
		ru: "xPUD быстро развивающийся проект. <br /> Больше информации можно получить здесь:",
		pl: "xPUD jest szybko rozwijającym się projektem. <br /> Jeśli chcesz dowiedzieć się więcej odwiedź:",
		vn: "xPUD là dự án đang phát triển nhanh <br /> Thông tin liên hệ tại:",
		el: "Το xPUD είναι συνεχώς υπο ανάπτυξη <br /> Για περισσότερες πληροφορίες στο:",
		ur: "تیزی سے ترقی پزیر پراجیکٹ ہے xPUD",
		cs: "xPUD je rychle se rozvíjející projekt. <br> Pro více informací bež na:",
		nl:"xPUD is een rap groeiend project. <br /> Voor meer informatie, ga naar:",
		fa: "xPUD به سرعت در حال گسترش است.<br>برای اطلاعات بیشتر مراجعه کنید به:",
		kr: "xPUD는 빠르게 개발되고 있는 프로젝트입니다. <br /> 더 많은 정보를 보시려면 이곳을 방문해 주십시오:",
	},

	help_done: {
		en: "Done",
		de: "OK",
		es: "Hecho",
		fi: "OK",
		fr: "OK",
		gl: "Feito",
		it: "OK",
		jp: "完成です",
		se: "Klar",
		zh: "完成",
		zh_cn:"完成",
		ru: "Ок",
		pl: "Zakończono",
		vn: "Hoàn tất",
		el: "OK",
		ur: "تمام",
		cs: "OK",
		nl:"OK",
		fa: "انجام شده",
		kr: "확인",
	},

// menu

	application: {
		en: "Applications",
		de: "Programme",
		es: "Aplicaciones",
		fi: "Sovellukset",
		fr: "Applications",
		gl: "Aplicaci&oacute;ns",
		it: "Applicazioni",
		jp: "アプリケーション",
		pt: "Aplica&#231;&#245;es",
		se: "Applikationer",
		zh: "所有應用程式",
		zh_cn:"所有应用程序",
		ru: "Программы",
		pl: "Programy",
		vn: "Ứng dụng",
		el: "Εφαρμογές",
		ur: "پروگرامز",
		fa: "نرم افزارهای کاربردی",
		cs: "Programy",
		nl:"Programma's",
		kr: "프로그램",
	},

	web_app: {
		en: "Web App",
		zh: "網頁捷徑",
		cs: "Web aplikace",
		nl:"Web App",
		fa: "نرم افزارهای تحت وب",
		kr: "인터넷 프로그램",
	},

	web_browser: {
		en: "Web Browser",
		de: "Web Browser",
		es: "Navegador web",
		fi: "Internet-selain",
		fr: "Navigateur Web",
		gl: "Navegador web",
		it: "Browser Web",
		jp: "ウェブブラウザ",
		pt: "Navegador de internet",
		se: "Webbläsare",
		zh: "網頁瀏覽器",
		zh_cn:"上网冲浪",
		ru: "Веб Браузер",
		pl: "Przeglądarka WWW",
		vn: "Trình duyệt Web",
		el: "Περιηγητής" ,
		ur: "ویب براوزر",
		cs: "Prohlížeč",
		nl:"Web Browser",
		fa: "مرورگر وب",
		kr: "인터넷 브라우저",
	},

	bt_client: {
		en: "BitTorrent Client",
		de: "BitTorrent Client",
		es: "Cliente BitTorrent",
		fi: "BitTorrent-asiakassovellus",
		fr: "Client BitTorrent",
		gl: "Cliente BitTorrent",
		it: "Client BitTorrent",
		jp: "ビットトレント",
		pt: "Cliente BitTorrent",
		se: "BitTorrent Klient",
		zh: "BT 下載",
		zh_cn:"BT 下载",
		ru: "Torrent клиент",
		pl: "Klient BitTorrent",
		vn: "BitTorrent",
		el: "Πελάτης BitTorrent",
		ur: "BitTorrent پروگرام برائے",
		cs: "BitTorrent klient",
		nl:"BitTorrent Client",
		fa: "کلاینت بیت تورنت",
		kr: "비트토렌트",
	},
	
	media_player: {
		en: "Media Player",
		de: "Media Player",
		es: "Reproductor multimedia",
		fi: "Mediasoitin",
		fr: "Lecteur Multimedia",
		gl: "Reproductor multimedia",
		it: "Lettore Multimediale",
		jp: "メディアプレーヤ",
		pt: "Reprodutor multim&#233;dia",
		se: "Mediaspelare",
		zh: "影音播放",
		zh_cn:"播放影音",
		ru: "Аудио/Видео проигрыватель",
		pl: "Odtwarzacz multimedialny",
		vn: "Đa phương tiện",
		el: "Αναπαραγωγή Πολυμέσων",
		ur: "میڈیا پلیئر",
		cs: "Přehrávač médií",
		nl:"Media Player",
		fa: "اجرا کننده چند رسانه ای",
		kr: "미디어 플레이어",
	},
	picture_viewer: {
		en: "Picture Viewer",
		de: "Bildbetrachter",
		es: "Visor de im&aacute;genes",
		fi: "Kuvienkatseluohjelma",
		fr: "Visionneur d'images",
		gl: "Visor de imaxes",
		it: "Visualizzatore di Immagini",
		jp: "ピクチャービューア",
		pt: "Visualizador de imagens",
		se: "Bildvisare",
		zh: "圖片瀏覽",
		zh_cn:"浏览图片",
		ru: "Просмотрщик изображений",
		pl: "Przeglądarka obrazów",
		vn: "Quản lý ảnh",
		el: "Εικόνες",
		ur: "تصویر دیکھنے کیلئے",
		cs: "Prohlížeč obrázků",
		nl:"Afbeeldingen Viewer",
		fa: "نمایش دهنده تصاویر",
		kr: "사진 보기",
	},
	text_editor: {
		en: "Text Editor",
		de: "Text Editor",
		es: "Editor de texto",
		fi: "Tekstinmuokkain",
		fr: "Éditeur de texte",
		gl: "Editor de texto",
		it: "Editor di Testo",
		jp: "テキストエディタ",
		pt: "Editor de texto",
		se: "Textredigerare",
		zh: "文字編輯",
		zh_cn:"编辑文字",
		ru: "Текстовый редактор",
		pl: "Edytor tekstu",
		vn: "Soạn thảo văn bản",
		el: "Κειμενογράφος",
		ur: "ٹیکسٹ لکھنے کیلئے",
		cs: "Textový editor",
		nl:"Tekstbewerker",
		fa: "ویرایشگر متن",
		kr: "문서 편집",
	},
	pdf_viewer: {
		en: "PDF Viewer",
		de: "PDF Viewer",
		es: "Visor de PDF",
		fi: "PDF-katselin",
		fr: "Visionneur de PDF",
		gl: "Visor de PDF",
		it: "Visualizzatore di PDF",
		jp: "PDFビューア",
		pt: "Visualizador de PDFs",
		se: "PDF läsare",
		zh: "PDF 閱讀",
		zh_cn:"阅读PDF",
		ru: "Просмотрщик PDF",
		pl: "Przeglądarka plików PDF",
		vn: "PDF Viewer",
		el: "Ανάγνωση PDF",
		ur: "دیکھنے کیلئے PDF",
		cs: "Prohlížeč PDF",
		nl:"PDF Viewer",
		fa: "نمایش دهنده PDF",
		kr: "PDF 뷰어",
	},
	terminal_emulator: {
		en: "Terminal Emulator",
		de: "Terminal Emulator",
		es: "Emulador de terminal",
		fi: "Komentorivi",
		fr: "Émulateur de terminal",
		gl: "Emulador de terminal",
		it: "Emulatore di Teminale",
		jp: "ターミナル　エミュレータ",
		pt: "Terminal",
		se: "Kommandotolk",
		zh: "終端機",
		zh_cn:"使用终端",
		ru: "Терминал/Коммандная строка",
		pl: "Emulator terminala",
		vn: "Terminal Emulator",
		el: "Τερματικό",
		ur: "دیکھنے کیلئے PDF",
		cs: "Terminál",
		nl:"Terminal Emulator",
		fa: "ترمینال",
		kr: "터미널",
	},
	
// setting

	setting_personal: {
		en: "Personal",
		de: "Pers&ouml;nliche Einstellungen",
		es: "Personal",
		fi: "Henkilökohtaiset asetukset",
		fr: "Personnel",
		gl: "Persoal",
		it: "Personale",
		jp: "個人設定",
		se: "Personliga inställningar",
		zh: "個人設定",
		zh_cn:"个人设置",
		ru: "Персональные настройки",
		pl: "Ustawienia osobiste",
		vn: "Cá nhân hóa",
		el: "Προσωπικά",
		ur: "ذاتی",
		cs: "Osobní nastavení",
		nl:"Persoonlijk",
		fa: "شحصی",
		kr: "사용자 설정",
	},
		setting_language: {
			en: "Language",
			de: "Sprache",
			es: "Idioma",
			fi: "Kieli",
			fr: "Langue",
			gl: "Idioma",
			it: "Lingua",
			jp: "言語の選択",
			se: "Språk",
			zh: "語言選項",
			zh_cn:"语言选项",
			ru: "Язык",
			pl: "Język",
			vn: "Ngôn ngữ",
			el: "Γλώσσα",
			ur: "زبان",
			cs: "Jazyk",
			nl:"Taal",
			fa: "زبانها",
			kr: "언어",
		},
		setting_language_desc: {
			en: "choose locale and keymap",
			de: "sprache und tastenbelegung",
			es: "elegir el idioma y la distribuci&oacute;n del teclado",
			fi: "valitse aluekohtaiset- ja näppäimistöasetukset",
			fr: "choisir la langue et la disposition du clavier",
			gl: "elixir o idioma e a distribuci&oacute;n do teclado",
			it: "scegli la lingua e la configurazione della tastiera",
			jp: "ローカライズとキーの切換",
			se: "språk- och tangentbordsinstälnningar",
			zh: "切換語系和鍵盤",
			zh_cn:"切换语系和键盘",
			ru: "Выберите язык и раскладку",
			pl: "wybierz język i układ klawiatury",
			vn: "Chọn địa phương và kiểu bàn phím",
			el: "επιλογή locale και keymap",
			ur: "جگہ اور کی بورڈ کا انتخاب",
			cs: "jazyk a rozložení klávesnice",
			nl:"Kies taal en toetsenbord indeling",
			fa: "مکان مورد نظر خود را انتخاب کنید.",
			kr: "언어와 키보드를 선택하십시오",
		}, 
		setting_time_date: {
			en: "Time & Date",
			de: "Datum und Uhrzeit",
			es: "Fecha y hora",
			fi: "Aika ja päivämäärä",
			fr: "Date et heure",
			gl: "Data e hora",
			it: "Data e Ora",
			jp: "時間と月日",
			pt: "Relógio",
			se: "Tid och Datum",
			zh: "時間日期",
			zh_cn:"时间与日期",
			ru: "Дата и Время",
			pl: "Data i czas",
			vn: "Thời gian",
			el: "Ημερομηνία και Ώρα",
			ur: "وقت اور تاریخ",
			cs: "Datum a čas",
			nl:"Tijd & Datum",
			fa: "تاریخ و وقت",
			kr: "시간과 날짜",
		},
		setting_time_date_desc: {
			en: "change system clock",
			de: "Systemuhr einstellen",
			es: "Cambiar la hora del sistema",
			fi: "Aseta järjestelmän kello",
			fr: "Changer l'heure du système",
			gl: "Cambiar a hora do sistema",
			it: "Cambia l'ora di Sistema",
			jp: "システムの日時を変更",
			pt: "Atualize o rel&#243;gio do sistema",
			se: "ändra systemtid",
			zh: "調整系統日期與時間",
			zh_cn:"调整系统的日期与时间",
			ru: "Настроить часы",
			pl: "ustaw zegar systemowy",
			vn: "Thay đổi thời gian hệ thống",
			el: "Αλλαγή ώρας συστήματος",
			ur: "سسٹم کے وقت کو تبدیل کریں",
			cs: "Změnit datum a čas",
			nl:"Systeemklok aanpassen",
			fa: "انجام تغییرات در ساعت",
			kr: "시스템 시간을 변경하십시오",
		},
		setting_backup: {
			en: "Backup",
			de: "Backup",
			es: "Copia de seguridad",
			fi: "Varmuuskopio",
			fr: "Sauvegarde",
			gl: "Copia de seguridade",
			it: "Copia di Backup",
			jp: "バックアップの設定",
			pt: "C&#243;pia de seguran",
			se: "Backup",
			zh: "儲存資料",
			zh_cn:"保存资料",
			ru: "Резервное сохранение",
			pl: "Kopia danych",
			vn: "Khôi phục",
			el: "Αντίγραφο ασφαλείας",
			ur: "بیک اپ",
			cs: "Záloha nastavení",
			nl:"Backup",
			fa: "پشتیبان گیری",
			kr: "백업",
		},
		setting_backup_desc: {
			en: "save your data and changes",
			de: "Daten und Einstellungen sichern",
			es: "Salvaguardar sus datos y modificaciones",
			fi: "tallenna tiedostosi ja tehdyt muutoksesi",
			fr: "Sauver vos données et modifications",
			gl: "Salvagardar os seus datos e modificaci&oacute;ns",
			it: "salva i tuoi dati e modifiche",
			jp: "設定と変更を保存",
			pt: "Mecanismo persistente",
			se: "Spara ditt data och inställningar",
			zh: "保留你的設定和資料",
			zh_cn:"保留你的设置和资料",
			ru: "Сохранить дату и изменения",
			pl: "Zachowaj dane i ustawienia",
			vn: "Lưu lại",
			el: "Αποθηκεύστε τα δεδομένα και τις προσωπικές επιλογές σας",
			ur: "اپنے ڈیٹا اور تبدیلیوں کو محفوظ کریں",
			cs: "Ulož data a nastavení",
			nl:"Gegevens en instellingen opslaan",
			fa: "ذخیره کردن تغییرات انجام شده در تاریخ",
			kr: "변경된 내용을 저장합니다",
		},
	setting_system: {
		en: "System",
		de: "System",
		es: "Sistema",
		fi: "Järjestelmä",
		fr: "Système",
		gl: "Sistema",
		it: "Sistema",
		jp: "システム設定",
		pt: "Sistema",
		se: "System",
		zh: "系統設定",
		zh_cn:"系统设置",
		ru: "Система",
		pl: "System",
		vn: "Hệ thống",
		el: "Σύστημα",
		ur: "سسٹم",
		cs: "Systém",
		nl:"Systeem",
		fa: "سامانه",
		kr: "시스템",
	},
	
		setting_wifi: {
			en: "WiFi",
			de: "WiFi",
			es: "WiFi",
			fi: "WiFi",
			fr: "WiFi",
			gl: "WiFi",
			it: "WiFi",
			jp: "WiFi",
			se: "WiFi",
			zh: "WiFi",
			zh_cn:"WiFi",
			ru: "WiFi",
			pl: "Sieć bezprzewodowa",
			vn: "WiFi",
			el: "WiFi",
			ur: "وائی فائی",
			cs: "WiFi",
			nl:"WiFi",
			fa: "WiFi",
			kr: "WiFi",
		},
		setting_wifi_desc: {
			en: "setup wireless connection",
			de: "drahtloses netzwerk einrichten",
			es: "Configurar la conexi&oacute;n inal&aacute;mbrica",
			fi: "asenna langaton yhteys",
			fr: "configurer la connexion sans fil",
			gl: "Configurar a conexi&oacute;n sen f&iacute;os",
			it: "configura la connessione senza fili",
			jp: "無線通信の設定",
			se: "Konfigurera trådlöst nätverk",
			zh: "使用無線網路連線",
			zh_cn:"使用无线网络",
			ru: "настроить беспроводное соединение",
			pl: "ustaw połączenia sieci bezprzewodowej",
			vn: "Cài đặt sự kết nối không dây",
			el: "Ρυθμίσεις Ασύρματης Σύνδεσης",
			ur: "وائرلیس کنکشن ترتیب دیں",
			cs: "Nastav bezdrátové připojení k síti",
			nl:"Draadloze verbinding instellen",
			fa: "فراهم کردن ارتباط وایرلس",
			kr: "무선인터넷을 설정합니다",
		},
			setting_wifi_title: {
				en: "Setup Wireless Network",
				de: "Drahtloses Netzwerk Setup",
				es: "Configurar la red inal&aacute;mbrica",
				fi: "Asenna langaton verkko",
				fr: "configurer le réseau sans fil",
				gl: "Configurar a rede sen f&iacute;os",
				it: "Imposta la Rete senza fili",
				jp: "無線ネットワークの設定",
				se: "Konfigurera trådlöst nätverk",
				zh: "連到無線網路",
				ru: "Настроить Беспроводную Сеть",
				pl: "Ustawienia sieci bezprzewodowej",
				vn: "Cài đặt mạng không dây",
				el: "Ρύθμισεις Ασύρματης Σύνδεσης",
				ur: "وائیرلیس نیٹ ورک ترتیب دیں",
				cs: "Nastavení bezdrátové sítě",
				nl:"Draadloos netwerk instellen",
				fa: "فراهم کردن شبگه وایرلس",
				kr: "무선 네트워크를 설정합니다 ",
			},
			setting_wifi_device: {
				en: "Network Device: ",
				de: "WiFi Netzwerk Ger&auml;t: ",
				es: "Dispositivo inal&aacute;mbrico: ",
				fi: "Verkkolaite: ",
				fr: "Interface réseau: ",
				gl: "Dispositivo sen f&iacute;os",
				it: "Periferica di Rete: ",
				jp: "ネットワークカード",
				se: "Trådlös enhet: ",
				zh: "網路卡: ",
				ru: "Устройство: ",
				pl: "Urządzenie sieciowe: ",
				vn: "Thiệt bị mạng",
				el: "Συσκευή Δικτύου:",
				ur: "نیٹ ورک آلہ",
				cs: "Síťové zařízení",
				nl:"Netwerkapparaat: ",
				fa: "ابزار شبکه",
				kr: "네트워크 장치",
			},
			setting_wifi_choose: {
				en: "Choose a network: ",
				de: "W&auml;le ein Netzwerk",
				es: "Elija una red: ",
				fi: "Valitse verkko: ",
				fr: "Choisissez un réseau: ",
				gl: "Elixa unha rede: ",
				it: "Scegli una rete: ",
				jp: "ネットワークの選択",
				pt: "Selecione qual rede você quer se conectar:",
				se: "Välj ett nätverk: ",
				zh: "選一個要連線的基地台: ",
				ru: "Выберите Сеть: ",
				pl: "Wybierz sieć: ",
				vn: "Chọn mạng",
				el: "Επιλέξτε Δίκτυο:",
				ur: "نیٹ ورک منتخب کریں",
				cs: "Vyber síť",
				nl:"Kies een netwerk: ",
				fa: "انتخاب کردن شبکه",
				kr: "네트워크를 선택하십시오",
			},
			setting_wifi_refresh: {
				en: "Refresh",
				de: "Aktualisieren",
				es: "Actualizar",
				fi: "Päivitä",
				fr: "Actualiser",
				gl: "Actualizar",
				it: "Aggiorna",
				jp: "リフレッシュ",
				se: "Sök",
				zh: "重新整理",
				ru: "Обновить",
				pl: "Odświerz",
				vn: "Làm mới",
				el: "Ανανέωση",
				ur: "تازہ دم کریں",
				cs: "Aktualizovat",
				nl:"Ververs",
				fa: "بازآوری",
				kr: "목록 새로 고침",
			},
			setting_wifi_password: {
				en: "Password:",
				de: "Passwort:",
				es: "Contraseña",
				fi: "Salasana:",
				fr: "Mot de passe",
				gl: "Contrasinal",
				jp: "パスワード",
				pt: "Senha:",
				se: "Lösenord",
				zh: "密碼:",
				ru: "Пароль:",
				pl: "Hasło:",
				vn: "Mật khẩu",
				el: "Κωδικός",
				ur: "پاس ورڈ",
				cs: "Heslo",
				nl:"Paswoord:",
				fa: "کلمه عبور",
				kr: "암호",
			},
			setting_wifi_connect: {
				en: "Connect",
				de: "Verbinden",
				es: "Conectar",
				fi: "Yhdistä",
				fr: "Connecter",
				gl: "Conectar",
				it: "Collegati",
				jp: "接続する",
				se: "Anslut",
				zh: "連線",
				ru: "Соединить",
				pl: "Połącz",
				vn: "Kết nối",
				el: "Σύνδεση",
				ur: "کنیکٹ",
				cs: "Připojit",
				nl:"Verbinden",
				fa: "برقراری ارتباط",
				kr: "연결",
			},
		setting_ethernet: {
			en: "Ethernet",
			de: "Ethernet",
			es: "Red cableada",
			fi: "Lankaverkko",
			fr: "Connexion filaire",
			gl: "Rede con f&iacute;os",
			it: "Ethernet",
			jp: "イーサネット",
			se: "Ethernet",
			zh: "有線網路",
			zh_cn:"有线网络",
			ru: "Локальная Сеть",
			pl: "Sieć ethernet",
			vn: "Mạng cục bộ",
			ελ: "Ethernet",
			ur: "ایتھرنیٹ",
			cs: "Síť ethernet",
			nl:"Ethernet",	
			fa: "Ethernet",
			kr: "Ethernet",
		},
		setting_ethernet_desc: {
			en: "setup wired connection",
			de: "kabelgebundenes netzwerk einrichten",
			es: "Configurar la conexi&oacute;n cableada",
			fi: "asenna lankayhteys",
			fr: "configurer la connexion filaire",
			gl: "Configurar a conexi&oacute;n con f&iacute;os",
			it: "configurare la connessione Internet",
			jp: "ケーブル接続の設定",
			pt: "Configure sua conex&#227;o de internet",
			se: "Konfigurera trådburet nätverk",
			zh: "連接到網際網路",
			zh_cn:"使用有线网络",
			ru: "настроить проводное соединение",
			pl: "ustaw kablowe połączenie sieci ethernet",
			vn: "Cài đặt kết nối có dây",
			el: "Ρυθμίσεις Ενσύρματης Σύνδεσης",
			ur: "لوکل ایریا کنکشن ترتیب دیں",
			cs: "nastavení kabelové připojení",
			nl:"bekabeld netwerk instellen",
			fa: "فراهم نمودن ارتباط سیمی",
			kr: "유선인터넷을 설정합니다",
		},
		setting_opt: {
			en: "Opt-Get",
			de: "Opt-Get",
			es: "Opt-Get",
			fi: "Opt-Get",
			fr: "Opt-Get",
			gl: "Opt-Get",
			it: "Opt-Get",
			jp: "Opt-Get",
			pt: "Opt-Get",
			se: "Opt-Get",
			zh: "Opt-Get",
			zh_cn:"Opt-Get",
			ru: "Opt-Get",
			pl: "Opt-Get",
			vn: "Opt-Get",
			el: "Opt-Get",
			ur: "Opt-Get",
			cs: "Opt-Get",
			nl:"Opt-Get",
			fa: "Opt-Get",
			kr: "Opt-Get",
		},
		setting_opt_desc: {
			en: "get more apps",
			de: "weitere programme installieren",
			es: "Obtener m&aacute;s aplicaciones",
			fi: "hae lisää sovelluksia",
			fr: "obtenir plus d'applications",
			gl: "Obter m&aacute;is aplicaci&oacute;ns",
			it: "ottieni pi&ugrave; applicazioni",
			jp: "もっと他のアプリケーション",
			pt: "Baixe mais aplica&#231;&#245;es",
			se: "Installera flera applikationer",
			zh: "安裝更多額外程式",
			zh_cn:"安装更多程序",
			ru: "установить дополнительные программы",
			pl: "pobierz więcej programów",
			vn: "Thêm ứng dụng",
			el: "Εγκατάσταση Πρόσθετων Εφαρμογών",
			ur: "مزید پروگرام حاصل کریں",
			cs: "získej více programů",
			nl:"Meer toepassingen verkrijgen",
			fa: "دریافت نرم افزارهای بیشتر",
			kr: "프로그램을 다운로드합니다",
		},
	
	setting_hardware: {
		en: "Hardware",
		de: "Hardware",
		es: "Hardware",
		fi: "Laitteisto",
		fr: "Matériel",
		gl: "Hardware",
		it: "Hardware",
		jp: "ハードウェア",
		se: "Hårdvara",
		zh: "硬體設定",
		zh_cn:"硬件设置",
		ru: "Оборудование",
		pl: "Sprzęt",
		vn: "Phần cứng",
		el: "Υλικό",
		ur: "ھارڈوئیر",
		cs: "Hardware",
		nl:"Hardware",
		fa: "سخت افزار",
		kr: "하드웨어",
	},
		setting_sound: {
			en: "Sound",
			de: "Ton",
			es: "Sonido",
			fi: "Äänet",
			fr: "Son",
			gl: "Son",
			it: "Audio",
			jp: "サウンド",
			pt: "&#193;udio",
			se: "Ljud",
			zh: "聲音",
			zh_cn:"声音",
			ru: "Звук",
			pl: "Dźwięk",
			vn: "Âm thanh",
			el: "Ήχος",
			ur: "آواز",
			cs: "Zvuk",
			nl:"Geluid",
			fa: "صدا",
			kr: "사운드",
		},
		setting_sound_desc: {
			en: "adjust system sound",
			de: "Systemkl&auml;nge einstellen",
			es: "Ajustar el sonido del sistema",
			fi: "Säädä järjestelmän ääniä",
			fr: "ajuster les sons système",
			gl: "Axustar o son do sistema",
			it: "configura le periferiche audio del sistema",
			jp: "システムの音量を設定",
			pt: "Ajustar som do sistema",
			se: "Ändra systemljud",
			zh: "調整系統音量設定",
			zh_cn:"调整系统音量",
			ru: "настроить звук",
			pl: "dostosuj ustawienia dźwięku",
			vn: "Điều chỉnh âm thanh",
			el: "Ρύθμιση ήχου",
			ur: "سسٹم کی آواز ترتیب دیں",
			cs: "Nastavení zvuku",
			nl:"Geluidsinstellingen",
			fa: "مرتب کردن سامانه صدا",
			kr: "시스템의 사운드를 조절합니다",
		},
		setting_display: {
			en: "Display",
			de: "Bildschirm",
			es: "Pantalla",
			fi: "Näyttö",
			fr: "Écran",
			gl: "Pantalla",
			it: "Schermo",
			jp: "ディスプレイ",
			pt: "Tela",
			se: "Bildskärm",
			zh: "螢幕",
			zh_cn:"显示设置",
			ru: "Экран",
			pl: "Ekran",
			vn: "Hiển thị",
			el: "Οθόνη",
			ur: "ڈسپلے",
			cs: "Zobrazení",
			nl:"Scherm",
			fa: "نمایشگر",
			kr: "디스플레이",
		},
		setting_display_desc: {
			en: "change screen resolution",
			de: "Aufl&ouml;sung einstellen",
			es: "Cambiar la resoluci&oacute;n de la pantalla",
			fi: "muuta näytön tarkkuutta",
			fr: "changer la résolution de l'écran",
			gl: "Cambiar a resoluci&oacute;n da pantalla",
			it: "cambia la risoluzione dello schermo",
			jp: "スクリーンのリゾリューションを変更",
			pt: "Alterar resolu&#231;&#227;o",
			se: "Ändra skärmupplösning",
			zh: "調整螢幕解析度",
			zh_cn:"调整屏幕分辨率",
			ru: "Изменить разрешение экрана",
			pl: "zmień ustawienia rozdzielczości",
			vn: "Chỉnh độ phân giải",
			el: "Αλλαγή ανάλυσης",
			ur: "سکرین کی ریزولوشن تبدیل کریں",
			cs: "Změna rozlišení obrazovky",
			nl:"Schermresolutie aanpassen",
			fa: "تغییر در نحوه نمایش ",
			kr: "화면 해상도를 조절합니다",
		},
		setting_driver: {
			en: "Driver",
			de: "Treiber",
			es: "Controladores",
			fi: "Ajuri",
			fr: "Pilotes",
			gl: "Controladores",
			it: "Driver",
			jp: "ドライバ",
			se: "Drivrutin",
			zh: "裝置管理",
			zh_cn:"驱动管理",
			ru: "Устройства",
			pl: "Sterownik",
			vn: "Driver phần cứng",
			el: "Οδηγός",
			ur: "ڈرائیور",
			cs: "Změna rozlišení obrazovky",
			nl:"Stuurprogramma",
			fa: "گرداننده ",
			kr: "드라이버",
		},
		setting_driver_desc: {
			en: "device info and driver",
			de: "ger&auml;teinformationen und treiber",
			es: "informaci&oacute;n de los controladores de los perif&eacute;ricos",
			fi: "tietoja laitteista ja ajureista",
			fr: "informations et drivers des périphériques",
			gl: "Informaci&oacute;n dos controladores dos perif&eacute;ricos",
			it: "informazioni su periferiche e drivers",
			jp: "デバイス情報とドライバ",
			se: "hårdvaruinformation och drivrutiner",
			zh: "安裝更多驅動程式",
			zh_cn:"安装更多驱动程序",
			ru: "информация об устройствах и драйверах",
			pl: "informacje o urzączeniu i sterownik",
			vn: "thiết bị và driver phần cứng",
			el: "Πληροφορίες συσκευών και οδηγών",
			ur: "آلہ کے بارے میں معلومات اور ڈرائیور",
			cs: "Informace o zařízeních a ovladačích",
			nl:"Apparaatinfo en stuurprogramma",
			fa: "ابزار و اطلاعات مربوط به گرداننده ها ",
			kr: "장치정보 및 드라이버",
		},
		setting_sysinfo: {
			en: "System Info",
			zh: "系統資訊",
			cs: "Systémové informace",
			nl:"Systeem Info",
			fa: "اطلاعات سامانه ",
			kr: "시스템 정보",
			el: "Πληροφορίες Συστήματος",
		},
		setting_sysinfo_desc: {
			en: "check system information",
			zh: "檢視系統狀態",
			cs: "zobraz systémové informace",
			nl:"controleer systeem info",
			fa: "بررسی اطلاعات سامانه ",
			kr: "시스템 정보를 확인합니다",
			el: "Έλεγχος Συστήματος",
		},
		
			back_to_setting: {
				en: "Back to Settings",
				de: "Zur&uuml;ck zu den Einstellungen",
				es: "Volver a Configuraci&oacute;n",
				fi: "Takaisin asetuksiin",
				fr: "Retour aux Paramètres",
				gl: "Volver a Configuraci&oacute;n",
				it: "Torna alle Impostazioni",
				jp: "設定に戻る",
				se: "Tillbaka till Inställningar",
				zh: "回到設定頁面",
				zh_cn: "返回设置",
				ru: "Назад к Настройкам",
				pl: "Wróć do ustawień",
				vn: "Quay lại Tùy chọn",
				el: "Επιστροφή στις Επιλογές",
				ur: "واپس سیٹنگز پر",
				cs: "Zpět do nastavení",
				nl:"Terug naar instellingen",
				fa: "بازگشت به قسمت مشخصه ها ",
				kr: "이전 화면으로",
		},

};
