#!/bin/sh
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export DISPLAY=:0
export GTK_IM_MODULE="scim"

	/bin/mount -t sysfs none /sys -onodev,noexec,nosuid
	/bin/mount -t proc none /proc -onodev,noexec,nosuid
	ln -s /proc/mounts /etc/mtab

	/usr/sbin/915resolution 32 1024 600 24
	/usr/sbin/915resolution -l > /tmp/915
	if grep -q '1024x600' /tmp/915; then
		RES=1024x600x24
	else
		RES=1024x768x24
	fi

	for x in $(cat /proc/cmdline); do
		case $x in
			screen=*)
				export RES=${x#screen=}
			;;
			lang=*)
				export UILANG=${x#lang=}
			;;
			kmap=*)
				export KEYMAP=${x#kmap=}
			;;
		esac
	done 
	
	# plate locale
	PLATE=/usr/share/plate/chrome/content
	if [ ! -z $UILANG ] && [ -e $PLATE/template.$UILANG ]; then 
		ln -s $PLATE/index.$UILANG.html $PLATE/index.html
		ln -s $PLATE/template.$UILANG $PLATE/template
	else
		ln -s $PLATE/index.en.html $PLATE/index.html
		ln -s $PLATE/template.en $PLATE/template
	fi

	/usr/local/bin/Xvesa :0 -ac -shadow -screen $RES -br -mouse mouse,/dev/input/mice &
	/bin/sleep 0.1
	TIME=`/bin/cat /proc/uptime | /bin/cut -d' ' -f 1` 
	/bin/sed -e s/xPUD.*9/"xPUD 0.8.9<br \/>Boot time - $TIME sec"/g /usr/share/plate/chrome/content/template/home.html.bak > /usr/share/plate/chrome/content/template/home.html 
	/usr/bin/firefox -app /usr/share/plate/application.ini &
	/sbin/session &
	/bin/sh
