#!/bin/sh
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export DISPLAY=:0
export GTK_IM_MODULE="scim"

	/bin/mount -t sysfs none /sys -onodev,noexec,nosuid
	/bin/mount -t proc none /proc -onodev,noexec,nosuid
	ln -sf /proc/mounts /etc/mtab

	for x in $(cat /proc/cmdline); do
		case $x in
			screen=*)
				export RES=${x#screen=}
			;;
			lang=*)
				export UILANG=${x#lang=}
			;;
			kmap=*)
				export KEYMAP=${x#kmap=}
			;;
		esac
	done 

	# keymap
	if [ ! -z $KEYMAP ] && [ -e /usr/share/keymap/$KEYMAP.kmap ]; then 
		loadkmap < /usr/share/keymap/$KEYMAP.kmap
	fi

	# plate locale
	PLATE=/usr/share/plate/chrome/content
	if [ ! -z $UILANG ] && [ -e $PLATE/index.$UILANG.html ]; then 
		UILANG=$UILANG
	else
		UILANG=en
	fi
	/bin/sed -e s/index.*html/"index.$UILANG.html"/g $PLATE/main.default > $PLATE/main.xul 

	# init hook
	find /etc/init.d/ -type f -exec {} \; 
	
	if [ -z $RES ]; then
		/usr/sbin/ddcprobe > /tmp/ddcprobe.log
		
		# try to override 38 (1280x1024) video mode 
		/usr/sbin/915resolution 38 1024 600 24
		/usr/sbin/915resolution -l > /tmp/915resolution.log

		# if succeeded
		if grep -q '1024x600' /tmp/915resolution.log; then
			export RES=1024x600x24
		else
			# get panel size from ddcprobe
			VMODE=`grep dtiming /tmp/ddcprobe.log | cut -d " " -f 2`
			# if panel size was found - set the screen resolution
			if  [ -z $VMODE ]; then
				export RES=1024x768x24
			else
				RES=`echo $VMODE | cut -d @ -f 1`
				/usr/sbin/915resolution 38 `echo ${RES/x/ }` 24
				export RES=`echo $RES"x24"`	
			fi 
		fi
	fi
	
	# start X server
	/usr/local/bin/Xvesa :0 -ac -shadow -screen $RES -br -mouse mouse,/dev/input/mice &
	/bin/sleep 0.1
	
	# start plate
	/usr/bin/firefox -app /usr/share/plate/application.ini &
	/sbin/session &
	/bin/sh
