#!/bin/bash

export DISPLAY=:0

exec &> /tmp/hotplug.log;

umask 0

add() {
	case "$SUBSYSTEM" in
		block)
			mknod /dev/$DEV b $MAJOR $MINOR
			mkdir -p /media/$DEV
			mount /dev/$DEV /media/$DEV
			#if [ `echo $DEV | wc -c` == 5 ]; then
			#/usr/bin/firefox file:///media/$DEV/ &
			#fi
			;;
		*)
			mknod /dev/$DEV c $MAJOR $MINOR
	esac
}

remove() {
	umount /media/$DEV
	rm /dev/$DEV
	
}

DEV=`basename $DEVPATH`

case "$ACTION" in
	add)
		add
		;;
	remove) 
		remove
		;;
	*)
		echo $0 $@ >> /tmp/hotplug.log
esac
