#!/bin/sh
export PATH="/sbin:/bin"

mount -o loop /opt/rootfs.sqf /ro
mount -t tmpfs tmpfs /rw
mount -t aufs -o br=/rw:/ro=ro none /newroot

mkdir -p /newroot/rofs /newroot/cow
mount --bind /ro /newroot/rofs
mount --bind /rw /newroot/cow

if [ -e /opt/*.opt ]; then 
for o in `ls /opt/*.opt`; do
	if [ -e $o ]; then
	mkdir -p $o.d
	mount -o loop $o $o.d 
	mount -o remount,append:$o.d /newroot
	fi
done
fi

switch_root /newroot /init
