#!/bin/sh
export PATH="/sbin:/bin"

# mounting procfs
mkdir /proc
mount -t proc proc /proc

# mounting sysfs
mkdir /sys
mount -t sysfs sysfs /sys 

mount -o loop /opt/rootfs.sqf /ro
mount -t tmpfs tmpfs /rw
mount -t aufs -o br=/rw:/ro=ro none /newroot

#mkdir -p /newroot/rofs /newroot/cow
#mount --bind /ro /newroot/rofs
#mount --bind /rw /newroot/cow

if [ -e /opt/*.opt ]; then 
for o in `ls /opt/*.opt`; do
	if [ -e ${o} ]; then
	mkdir -p ${o}.d
	mount -o loop ${o} ${o}.d 
	mount -o remount,append:${o}.d /newroot
	# moving optfs into new aufs filesystem
	mkdir -p /newroot/roopt/${o}.d
	mount --move ${o}.d /newroot/roopt/${o}.d
	fi
done
fi

# moving procfs into new aufs filesystem
mkdir -p /newroot/proc
mount --move /proc /newroot/proc

# moving sysfs into new aufs filesystem
mkdir -p /newroot/sys
mount --move /sys /newroot/sys

# moving readonly into new aufs filesystem
mkdir -p /newroot/rofs
mount --move /ro /newroot/rofs

# moving readwrite into new aufs filesystem
mkdir -p /newroot/cow
mount --move /rw /newroot/cow

# change root!
switch_root /newroot /init
