(function(){
function c(a,b,d){var e="on"+b;if(a.addEventListener)a.addEventListener(b,d,false);else if(a.attachEvent)a.attachEvent(e,d);else{var f=a[e];a[e]=function(){var g=f.apply(this,arguments),k=d.apply(this,arguments);return g==undefined?k:(k==undefined?g:k&&g)}}};var h,i,j,l="",o=null,p=null,q=null,r=-1,s,t,u,v,w,x,y,z=0,A=0,B=null,D=0;var K="clients1.google.com";
function ba(a,b,d,e){s=a;t=b;y="/complete/search?hl="+google.kHL;c(s,"submit",M);t.setAttribute("autocomplete","off");c(t,"blur",N);t.onkeypress=O;c(t,"keyup",
P);i=(j=(h=t.value));u=document.createElement("table");u.cellSpacing=(u.cellPadding="0");v=u.style;
u.className="gac_m";document.body.appendChild(u);N();R();c(window,"resize",R);c(window,"pageshow",function(m){if(m.persisted){w.value="f";x.value=t.value}});w=T("aq","f");x=T("oq",i);var f=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(f);var g=null;g=f.sheet;var n=function(m,Y){var Z=m+" { "+Y+" }";g.insertRule(Z,g.cssRules.length);};n(".gac_m","font-size:13px;cursor:default;line-height:17px;border:1px solid black;z-index:99;background:white;position:absolute;margin:0;");n(".gac_b","background:#36c;color:white;");
var C="white-space:nowrap;overflow:hidden;text-align:left;padding-left:3px;";n(".gac_c",C);n(".gac_d","white-space:nowrap;overflow:hidden;text-align:right;font-size:10px;color:green;padding:0 3px");n(".gac_b td","color:white");n(".gac_e td","padding:0 3px 2px;text-align:right;font-size:10px;line-height:15px");n(".gac_e span","color:#00c;text-decoration:underline;cursor:pointer");
U();(new Image).src="http://"+K+"/gen_204";}function R(){if(u){v.left=V(t,"offsetLeft")+"px";v.top=V(t,"offsetTop")+t.offsetHeight-1+"px";v.width=t.offsetWidth+"px";}}function T(a,b){var d=document.createElement("input");d.type="hidden";d.name=a;d.value=b;return s.appendChild(d)}
function O(a){var b=a.keyCode;if(b==27&&ca()){N();W(i);a.cancelBubble=true;return a.returnValue=false}if(b==38||b==40){A++;if(A%3==1)S(b);return false}}function P(a){var b=a.keyCode;if(A==0)S(b);A=0;}function S(a){if(t.value!=h){i=t.value;x.value=i}a==40&&da(r+1);a==38&&da(r-1);R();if(l!=i&&!B)B=window.setTimeout(N,500);h=t.value;if(h==""&&!o)U()}function ea(){if(D)return;if(q)q.className="gac_a";this.className="gac_b";q=this;for(var a=0,b;b=p[a];a++)b==q&&(r=a)}function da(a){if(!l&&i){j="";U();return}if(i!=l||!o)return;if(!p||p.length<=0)return;if(!ca()){X();return}var b=p.length-1;if(q)q.className="gac_a";if(a==b||a==-1){r=-1;W(i);t.focus();
w.value="f";return}else if(a>b)a=0;else if(a<-1)a=b-1;r=a;q=p.item(a);q.className="gac_b";W(q.completeString);w.value=q.completeId}function N(){if(B){window.clearTimeout(B);B=null}v.visibility="hidden";}function X(){v.visibility="visible";R();D=1}function ca(){return v.visibility==
"visible"}function fa(a){z>0&&z--;if(a[0]!=i)return;if(B){window.clearTimeout(B);B=null}l=a[0];u.innerHTML="";var b=0;for(var d=0,e;d<a[1].length;d++)if(e=a[1][d]){b++;var f=u.insertRow(-1);f.onclick=function(){
W(this.completeString);M();s.submit();};f.onmousedown=ga;f.onmouseover=ea;f.onmousemove=function(){if(D){D=0;ea.call(this)}};f.completeString=e[0];f.completeId=e[2];f.className="gac_a";var g=document.createElement("td");$(g,e[0]);g.className="gac_c";f.appendChild(g);var k=document.createElement("td");$(k,e[1]);k.className="gac_d";f.appendChild(k)}if(b>0){var n=u.insertRow(-1);n.onmousedown=ga;var C=document.createElement("td");C.colSpan=2;n.className="gac_e";var m=document.createElement("span");n.appendChild(C);C.appendChild(m);$(m,"close");m.onclick=function(){N();l="";window.clearTimeout(o);o=null;w.value="x"}}
r=-1;p=u.rows;(p.length>0?X:N)()}function M(){N();if(x.value!=t.value)w.value=p.item(r).completeId;else{x.value="";if(z>=10)w.value="o"}}function U(){if(j!=i&&i){z++;var a=document.createElement("script");a.setAttribute("id","gac_a");a.src="http://"+K+y+"&q="+encodeURIComponent(i);var b=document.getElementById("gac_a"),
d=document.getElementsByTagName("head")[0];if(b)d.removeChild(b);d.appendChild(a);t.focus()}j=i;var e=100;for(var f=1;f<=(z-2)/2;++f)e*=2;e+=50;o=window.setTimeout(U,e)}function W(a){t.value=a;h=a}function V(a,b){var d=0;while(a){d+=a[b];a=a.offsetParent}return d}function $(a,b){a.appendChild(document.createTextNode(b))}function ga(a){a.stopPropagation();
return false}window.google.ac={i:ba,h:fa};
})();
google.doFirst=function(){if(!google.xjs_ready)window.setTimeout(google.doFirst,10);else{if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(var a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.x=function(d,c){c&&c.apply(d);return false}}};google.doFirst();
